import { SEED_STORIES } from '@/utils/seedData';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://api.dreamvalley.app';

function getStoryTypeLabel(type) {
  switch (type) {
    case 'poem': return 'Poem';
    case 'song': return 'Lullaby';
    case 'long_story': return 'Long Story';
    default: return 'Story';
  }
}

function getStoryLanguage(story) {
  // Hindi stories are in SEED_STORIES.hi
  const hiStories = SEED_STORIES.hi || [];
  return hiStories.some((s) => s.id === story.id) ? 'hi' : 'en';
}

async function fetchStoryFromAPI(id) {
  try {
    const res = await fetch(`${API_URL}/api/v1/content/${id}`, {
      next: { revalidate: 3600 }, // cache for 1 hour
    });
    if (!res.ok) return null;
    const json = await res.json();
    return json.data || null;
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }) {
  const { id } = await params;

  // Look up story in seed data (both en and hi arrays)
  const allStories = [...(SEED_STORIES.en || []), ...(SEED_STORIES.hi || [])];
  let story = allStories.find((s) => s.id === id);

  // Fallback: fetch from backend API for stories added after last build
  if (!story) {
    story = await fetchStoryFromAPI(id);
  }

  if (!story) {
    return {
      title: 'Dream Valley - Listen to a Story',
      description: 'Magical bedtime stories for kids — listen now on Dream Valley.',
    };
  }

  const title = `${story.title} | Dream Valley`;
  const typeLabel = getStoryTypeLabel(story.type);
  const lang = getStoryLanguage(story);
  const description =
    story.description ||
    `Listen to "${story.title}" — a magical bedtime ${typeLabel.toLowerCase()} for kids on Dream Valley.`;

  const keywords = [
    story.title,
    `${typeLabel.toLowerCase()} for kids`,
    'bedtime stories',
    'kids sleep stories',
    ...(story.categories || []),
    ...(story.theme ? [story.theme] : []),
    lang === 'hi' ? 'Hindi bedtime stories' : 'English bedtime stories',
    'dream valley',
  ].join(', ');

  // OG image auto-generated by opengraph-image.js in this directory
  return {
    title,
    description,
    keywords,
    alternates: {
      canonical: `https://dreamvalley.app/player/${id}`,
    },
    openGraph: {
      title: story.title,
      description,
      type: 'article',
      siteName: 'Dream Valley',
      url: `https://dreamvalley.app/player/${id}`,
      locale: lang === 'hi' ? 'hi_IN' : 'en_US',
      images: [{
        url: `https://dreamvalley.app/player/${id}/opengraph-image`,
        width: 1200,
        height: 630,
        alt: story.title,
      }],
    },
    twitter: {
      card: 'summary_large_image',
      title: story.title,
      description,
      images: [`https://dreamvalley.app/player/${id}/opengraph-image`],
    },
  };
}

export default function PlayerLayout({ children }) {
  return children;
}
