import { SEED_STORIES } from '@/utils/seedData';

function getStoryTypeLabel(type) {
  switch (type) {
    case 'poem': return 'Poem';
    case 'song': return 'Lullaby';
    case 'long_story': return 'Long Story';
    default: return 'Story';
  }
}

function getStoryLanguage(story) {
  // Hindi stories are in SEED_STORIES.hi
  const hiStories = SEED_STORIES.hi || [];
  return hiStories.some((s) => s.id === story.id) ? 'hi' : 'en';
}

export async function generateMetadata({ params }) {
  const { id } = await params;

  // Look up story in seed data (both en and hi arrays)
  const allStories = [...(SEED_STORIES.en || []), ...(SEED_STORIES.hi || [])];
  const story = allStories.find((s) => s.id === id);

  if (!story) {
    return {
      title: 'Dream Valley - Listen to a Story',
      description: 'Magical bedtime stories for kids — listen now on Dream Valley.',
    };
  }

  const title = `${story.title} | Dream Valley`;
  const typeLabel = getStoryTypeLabel(story.type);
  const lang = getStoryLanguage(story);
  const description =
    story.description ||
    `Listen to "${story.title}" — a magical bedtime ${typeLabel.toLowerCase()} for kids on Dream Valley.`;

  const keywords = [
    story.title,
    `${typeLabel.toLowerCase()} for kids`,
    'bedtime stories',
    'kids sleep stories',
    ...(story.categories || []),
    ...(story.theme ? [story.theme] : []),
    lang === 'hi' ? 'Hindi bedtime stories' : 'English bedtime stories',
    'dream valley',
  ].join(', ');

  // OG image auto-generated by opengraph-image.js in this directory
  return {
    title,
    description,
    keywords,
    alternates: {
      canonical: `https://dreamvalley.app/player/${id}`,
    },
    openGraph: {
      title: story.title,
      description,
      type: 'article',
      siteName: 'Dream Valley',
      url: `https://dreamvalley.app/player/${id}`,
      locale: lang === 'hi' ? 'hi_IN' : 'en_US',
    },
    twitter: {
      card: 'summary_large_image',
      title: story.title,
      description,
    },
  };
}

export default function PlayerLayout({ children, params }) {
  // Build JSON-LD for this story (server component — runs at request time)
  const allStories = [...(SEED_STORIES.en || []), ...(SEED_STORIES.hi || [])];
  const story = allStories.find((s) => s.id === params.id);

  if (!story) return children;

  const typeLabel = getStoryTypeLabel(story.type);
  const lang = getStoryLanguage(story);

  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Article',
        '@id': `https://dreamvalley.app/player/${story.id}#article`,
        headline: story.title,
        description:
          story.description ||
          `A magical bedtime ${typeLabel.toLowerCase()} for kids`,
        inLanguage: lang,
        author: {
          '@type': 'Organization',
          name: 'Dream Valley',
          url: 'https://dreamvalley.app',
        },
        publisher: {
          '@type': 'Organization',
          name: 'Dream Valley',
          url: 'https://dreamvalley.app',
          logo: {
            '@type': 'ImageObject',
            url: 'https://dreamvalley.app/apple-touch-icon.png',
          },
        },
        mainEntityOfPage: `https://dreamvalley.app/player/${story.id}`,
        genre: typeLabel,
        audience: {
          '@type': 'Audience',
          audienceType: 'Children',
          suggestedMinAge: story.target_age?.split('-')[0] || '2',
          suggestedMaxAge: story.target_age?.split('-')[1] || '10',
        },
        isAccessibleForFree: true,
        ...(story.duration
          ? { timeRequired: `PT${Math.ceil(story.duration / 60)}M` }
          : {}),
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          {
            '@type': 'ListItem',
            position: 1,
            name: 'Home',
            item: 'https://dreamvalley.app',
          },
          {
            '@type': 'ListItem',
            position: 2,
            name: 'Explore',
            item: 'https://dreamvalley.app/explore',
          },
          {
            '@type': 'ListItem',
            position: 3,
            name: story.title,
            item: `https://dreamvalley.app/player/${story.id}`,
          },
        ],
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      {children}
    </>
  );
}
