import { Suspense } from 'react';
import Script from 'next/script';
import { Fraunces, Quicksand, Tiro_Devanagari_Hindi } from 'next/font/google';
import './globals.css';
import AppShell from '@/components/AppShell';
import PostHogProvider from '@/components/PostHogProvider';
import PostHogPageview from '@/components/PostHogPageview';

const GA4_ID = process.env.NEXT_PUBLIC_GA4_ID;

const quicksand = Quicksand({ subsets: ['latin'], variable: '--font-dream-ui' });
const fraunces = Fraunces({ subsets: ['latin'], variable: '--font-dream-display' });
const tiroHindi = Tiro_Devanagari_Hindi({
  subsets: ['devanagari'],
  weight: '400',
  variable: '--font-dream-devanagari',
});

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

export const metadata = {
  metadataBase: new URL('https://dreamvalley.app'),
  themeColor: '#0D0B2E',
  title: 'Dream Valley — Bedtime Stories That Help Kids Fall Asleep',
  description:
    'AI-generated bedtime stories every night with calming narration, original ambient music, and living animated art. Dream Valley guides your child from wide awake to sound asleep through sleep science.',
  keywords:
    'bedtime stories for kids, children bedtime stories, AI bedtime stories, kids sleep stories, ' +
    'lullabies for babies, bedtime poems for children, sleep stories for toddlers, ' +
    'kids story app, bedtime story app, children lullaby app, ' +
    'soothing stories for kids, calming bedtime stories, ' +
    'Hindi bedtime stories, Hindi lullabies for kids, ' +
    'dream valley, dream valley stories',
  category: 'education',
  creator: 'Dream Valley',
  publisher: 'Dream Valley',
  alternates: {
    canonical: 'https://dreamvalley.app',
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Dream Valley',
  },
  openGraph: {
    title: 'Dream Valley — Bedtime Stories That Help Kids Fall Asleep',
    description:
      'AI-generated bedtime stories with calming narration, original music, and living animated art that guides your child to sleep.',
    type: 'website',
    siteName: 'Dream Valley',
    url: 'https://dreamvalley.app',
    locale: 'en_US',
    // OG image auto-generated by opengraph-image.js
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Dream Valley — Bedtime Stories That Help Kids Fall Asleep',
    description:
      'AI-generated bedtime stories with calming narration, original music, and living animated art that guides your child to sleep.',
    // OG image auto-generated by opengraph-image.js
  },
};

// JSON-LD structured data for Organization + WebSite (homepage SEO)
const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': 'https://dreamvalley.app/#organization',
      name: 'Dream Valley',
      url: 'https://dreamvalley.app',
      logo: {
        '@type': 'ImageObject',
        url: 'https://dreamvalley.app/apple-touch-icon.png',
      },
      description:
        'Dream Valley creates soothing AI-narrated bedtime stories, poems, and lullabies for children.',
      sameAs: [],
    },
    {
      '@type': 'WebSite',
      '@id': 'https://dreamvalley.app/#website',
      url: 'https://dreamvalley.app',
      name: 'Dream Valley',
      description: 'Magical bedtime stories, poems, and lullabies for kids',
      publisher: { '@id': 'https://dreamvalley.app/#organization' },
      potentialAction: {
        '@type': 'SearchAction',
        target: {
          '@type': 'EntryPoint',
          urlTemplate: 'https://dreamvalley.app/explore?q={search_term_string}',
        },
        'query-input': 'required name=search_term_string',
      },
    },
    {
      '@type': 'WebApplication',
      '@id': 'https://dreamvalley.app/#app',
      name: 'Dream Valley',
      url: 'https://dreamvalley.app',
      applicationCategory: 'EducationalApplication',
      operatingSystem: 'iOS, Web',
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
      },
      description:
        'Free bedtime story app with AI-narrated stories, poems, and lullabies for children.',
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${quicksand.variable} ${fraunces.variable} ${tiroHindi.variable}`}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var c=window.crypto||window.msCrypto;if(c&&!c.randomUUID&&c.getRandomValues){c.randomUUID=function(){var b=c.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;var s='';for(var i=0;i<16;i++){s+=(b[i]+256).toString(16).slice(1);if(i===3||i===5||i===7||i===9)s+='-';}return s;};}}catch(e){}})();",
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {GA4_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${GA4_ID}`}
              strategy="afterInteractive"
            />
            <Script id="ga4-init" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                window.gtag = gtag;
                gtag('js', new Date());
                gtag('config', '${GA4_ID}', { send_page_view: false });
              `}
            </Script>
          </>
        )}
      </head>
      <body className={quicksand.className}>
        <PostHogProvider>
          <Suspense fallback={null}>
            <PostHogPageview />
          </Suspense>
          <AppShell>{children}</AppShell>
        </PostHogProvider>
      </body>
    </html>
  );
}
