/**
 * Fallback seed data for when the backend is unreachable.
 * English + Hindi versions keyed by language.
 * Cover images are local SVG illustrations with consistent mystical/dreamy style.
 */

// Cover images — mystical dreamy SVG illustrations in /public/covers/
const COVERS = {
  sleepyCloud: '/covers/sleepy-cloud.svg',
  braveFirefly: '/covers/brave-firefly.svg',
  moonLullaby: '/covers/moon-lullaby.svg',
  captainStardust: '/covers/captain-stardust.svg',
  gardenWhispers: '/covers/garden-whispers.svg',
  twinkleDream: '/covers/twinkle-dream.svg',
  owlGoodnight: '/covers/owl-goodnight.svg',
  sailingDreamland: '/covers/sailing-dreamland.svg',
};

export const SEED_STORIES = {
  en: [
    {
      id: "seed-sleepy-cloud",
      type: "story",
      title: "The Sleepy Cloud",
      description: "A fluffy cloud drifts across the moonlit sky, collecting dreams for sleepy children.",
      cover: COVERS.sleepyCloud,
      text: "High above the rooftops, a fluffy little cloud named Nimbus floated gently through the night sky. Nimbus had the most important job in all the world \u2014 collecting sweet dreams from the stars and sprinkling them over sleeping children.\n\nTonight, the stars were especially sparkly. Nimbus reached out with soft, cottony arms and caught a dream about flying horses, another about a garden made entirely of candy, and one more about a friendly dragon who loved to share warm hugs.\n\nAs Nimbus drifted over your house, it gently shook its fluffy body, and the dreams floated down like tiny snowflakes. They landed softly on your pillow, waiting for you to close your eyes.\n\n\"Sweet dreams, little one,\" whispered Nimbus, as it continued its journey across the peaceful night sky, leaving a trail of starlight behind.",
      target_age: 4,
      duration: 3,
      like_count: 57,
      save_count: 88,
      view_count: 160,
      categories: ["Fantasy", "Lullabies", "Magical"],
      theme: "dreamy",
      musicProfile: "dreamy-clouds",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/7fe248e1_female_1.mp3", duration_seconds: 73.34 },
        { voice: "female_2", url: "/audio/pre-gen/7fe248e1_female_2.mp3", duration_seconds: 79.79 },
        { voice: "male_1", url: "/audio/pre-gen/7fe248e1_male_1.mp3", duration_seconds: 66.34 },
      ],
    },
    {
      id: "seed-brave-firefly",
      type: "story",
      title: "The Brave Little Firefly",
      description: "A tiny firefly discovers its light can guide lost animals home.",
      cover: COVERS.braveFirefly,
      text: "In the heart of Whispering Woods lived a tiny firefly named Flicker. Unlike the other fireflies who shone brilliant gold, Flicker\u2019s light was small and soft.\n\nBut that very night, a baby rabbit named Clover got lost in the darkest part of the forest. \"Follow my light!\" said Flicker. And though the glow was small, it was just enough for Clover to see each step of the way.\n\nTogether, they walked through the forest, Flicker lighting the path one step at a time, until they reached Clover\u2019s burrow where Mama Rabbit was waiting.\n\n\"Thank you, little light,\" said Clover. \"You're the bravest firefly in all the woods.\"\n\nAnd from that night on, Flicker never felt small again. Because even the tiniest light can guide someone home.",
      target_age: 5,
      duration: 4,
      like_count: 92,
      save_count: 16,
      view_count: 191,
      categories: ["Animals", "Adventure", "Friendship"],
      theme: "adventure",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/8e516449_female_1.mp3", duration_seconds: 97.39 },
        { voice: "female_2", url: "/audio/pre-gen/8e516449_female_2.mp3", duration_seconds: 105.24 },
        { voice: "male_1", url: "/audio/pre-gen/8e516449_male_1.mp3", duration_seconds: 88.94 },
      ],
    },
    {
      id: "seed-moons-lullaby",
      type: "story",
      title: "The Moon's Lullaby",
      description: "The Moon sings a gentle song to help all the animals fall asleep.",
      cover: COVERS.moonLullaby,
      text: "When the sun tucked itself behind the hills, the Moon rose slowly, casting a soft silver glow over Willow Meadow.\n\n\"Hush now, little fox,\" the Moon sang softly, and the fox curled up in its cozy den.\n\n\"Rest now, little owl,\" the Moon hummed, and the owl tucked its head under its wing.\n\nAnd then the Moon looked down at you and sang the sweetest note of all: \"Goodnight, my little dreamer. The stars will watch over you until morning comes.\"\n\nAnd with that, the whole world fell into a peaceful, happy sleep.",
      target_age: 3,
      duration: 3,
      like_count: 99,
      save_count: 10,
      view_count: 427,
      categories: ["Lullabies", "Animals", "Nature"],
      theme: "fairy_tale",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/30dec3e8_female_1.mp3", duration_seconds: 90.04 },
        { voice: "female_2", url: "/audio/pre-gen/30dec3e8_female_2.mp3", duration_seconds: 96.84 },
        { voice: "male_1", url: "/audio/pre-gen/30dec3e8_male_1.mp3", duration_seconds: 81.85 },
      ],
    },
    {
      id: "seed-captain-stardust",
      type: "story",
      title: "Captain Stardust and the Comet Race",
      description: "A space explorer races comets to deliver a birthday wish.",
      cover: COVERS.captainStardust,
      text: "Captain Stardust adjusted her sparkly helmet and gripped the controls of her starship, the Silver Dreamer. Tonight\u2019s mission \u2014 deliver a birthday wish to Planet Cakealot before midnight!\n\nThe Silver Dreamer zoomed past Saturn\u2019s rings, weaved through an asteroid field, and raced alongside a brilliant blue comet named Flash.\n\nThey arrived just in time! Captain Stardust delivered the wish \u2014 a glowing golden star.\n\n\"Mission complete,\" she smiled. \"Even space explorers need their sleep.\"\n\nAnd as the Silver Dreamer sailed home, the stars whispered goodnight.",
      target_age: 7,
      duration: 4,
      like_count: 109,
      save_count: 84,
      view_count: 394,
      categories: ["Space", "Adventure"],
      theme: "space",
      musicProfile: "cosmic-voyage",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/d73e9530_female_1.mp3", duration_seconds: 114.94 },
        { voice: "female_2", url: "/audio/pre-gen/d73e9530_female_2.mp3", duration_seconds: 123.99 },
        { voice: "male_1", url: "/audio/pre-gen/d73e9530_male_1.mp3", duration_seconds: 106.39 },
      ],
    },
    {
      id: "seed-garden-whispers",
      type: "story",
      title: "The Garden of Whispers",
      description: "A magical garden where flowers tell stories to anyone who listens.",
      cover: COVERS.gardenWhispers,
      text: "Behind Grandmother\u2019s house, Maya found a garden that shimmered with golden light. The flowers were magical \u2014 roses that glowed like lanterns, lilies that hummed melodies.\n\nEach flower held a different story. The daisies told tales of brave mice. The tulips shared legends of kindness. The lavender whispered poems about starlit nights.\n\nEvery story ended the same way: \"Close your eyes now, dear listener. Tomorrow, there will be another story waiting just for you.\"",
      target_age: 8,
      duration: 5,
      like_count: 181,
      save_count: 36,
      view_count: 129,
      categories: ["Magical", "Fantasy", "Nature"],
      theme: "fantasy",
      musicProfile: "enchanted-garden",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/9fba7605_female_1.mp3", duration_seconds: 121.74 },
        { voice: "female_2", url: "/audio/pre-gen/9fba7605_female_2.mp3", duration_seconds: 130.24 },
        { voice: "male_1", url: "/audio/pre-gen/9fba7605_male_1.mp3", duration_seconds: 113.14 },
      ],
    },
    {
      id: "seed-twinkle-dream",
      type: "poem",
      title: "Twinkle Dream",
      description: "A gentle bedtime poem about stars watching over sleeping children.",
      cover: COVERS.twinkleDream,
      text: "The stars above are blinking bright,\nThey guard your dreams throughout the night.\nThe moon is smiling, round and white,\nAnd wraps the world in silver light.\n\nSo close your eyes, my little one,\nThe day is done, the night\u2019s begun.\nTomorrow brings a brand new sun,\nBut now it\u2019s time for sleep and fun.",
      target_age: 3,
      duration: 2,
      like_count: 27,
      save_count: 82,
      view_count: 386,
      categories: ["Lullabies", "Magical"],
      theme: "dreamy",
      musicProfile: "starlight-lullaby",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/c8796852_female_1.mp3", duration_seconds: 38.59 },
        { voice: "female_2", url: "/audio/pre-gen/c8796852_female_2.mp3", duration_seconds: 39.73 },
        { voice: "male_1", url: "/audio/pre-gen/c8796852_male_1.mp3", duration_seconds: 36.94 },
      ],
    },
    {
      id: "seed-owls-goodnight",
      type: "poem",
      title: "The Owl's Goodnight",
      description: "A wise owl says goodnight to every creature in the forest.",
      cover: COVERS.owlGoodnight,
      text: "Hoo-hoo, says the owl from the old oak tree,\nGoodnight to the fish in the deep blue sea.\nGoodnight to the rabbits in burrows so snug,\nGoodnight to the ladybug under the rug.\n\nHoo-hoo, says the owl to the fox in its den,\nTo the duck and the drake and the little brown hen.\nGoodnight to the squirrel with acorns to keep,\nHoo-hoo, little darling \u2014 it\u2019s time now to sleep.",
      target_age: 2,
      duration: 2,
      like_count: 133,
      save_count: 60,
      view_count: 200,
      categories: ["Animals", "Lullabies"],
      theme: "animals",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/e32eaee0_female_1.mp3", duration_seconds: 32.34 },
        { voice: "female_2", url: "/audio/pre-gen/e32eaee0_female_2.mp3", duration_seconds: 33.1 },
        { voice: "male_1", url: "/audio/pre-gen/e32eaee0_male_1.mp3", duration_seconds: 30.65 },
      ],
    },
    {
      id: "seed-sailing-dreamland",
      type: "song",
      title: "Sailing to Dreamland",
      description: "A gentle lullaby about sailing to the land of dreams.",
      cover: COVERS.sailingDreamland,
      text: "[Verse 1]\nWe\u2019re sailing on a silver boat,\nAcross the moonlit sea.\nThe stars are singing lullabies,\nFor you and me.\n\n[Chorus]\nDreamland, dreamland, just close your eyes,\nSail away under purple skies.\nDreamland, dreamland, the night is kind,\nLeave all your worries far behind.",
      target_age: 4,
      duration: 2,
      like_count: 20,
      save_count: 25,
      view_count: 285,
      categories: ["Lullabies", "Magical"],
      theme: "dreamy",
      musicProfile: "ocean-drift",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/a3945b7b_female_1.mp3", duration_seconds: 48.04 },
        { voice: "female_2", url: "/audio/pre-gen/a3945b7b_female_2.mp3", duration_seconds: 57.04 },
        { voice: "male_1", url: "/audio/pre-gen/a3945b7b_male_1.mp3", duration_seconds: 44.04 },
      ],
    },
  ],
  hi: [
    {
      id: "seed-neendwala-badal",
      type: "story",
      title: "Neendwala Badal",
      description: "Ek narm-mulaayam badal chaandni raat mein sapne baat-ta phirta hai.",
      cover: COVERS.sleepyCloud,
      text: "Chhat ke upar aasmaan mein, ek chhota sa mulaayam badal tha jiska naam tha Nimbus. Nimbus ka kaam duniya ka sabse khaas kaam tha \u2014 taaron se meethe sapne ikaththa karna aur sote hue bacchon pe chidakna.\n\nAaj raat taare khoob chamak rahe the. Nimbus ne apne narm haathon se ek sapna pakda \u2014 udne waale ghode ka, ek aur candy ke baag ka, aur ek pyaare dragon ka jo garam jhappi dena chahta tha.\n\nJab Nimbus tumhare ghar ke upar se guzra, usne apna phulphula badan hilaya, aur sapne chhoti chhoti barf ki phuhar ki tarah neeche aaye. Wo tumhare takkiye pe aaram se baith gaye, tumhara aankhein band karne ka intezaar kar rahe the.\n\n\"Meethe sapne dekho, chhote,\" Nimbus ne dheere se kaha, aur chaandni ki lakeer chhodta hua aage nikal gaya.",
      target_age: 4,
      duration: 3,
      like_count: 57,
      save_count: 88,
      view_count: 160,
      categories: ["Kalpana", "Lori", "Jaadui"],
      theme: "dreamy",
      musicProfile: "dreamy-clouds",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-neend_female_1_hi.mp3", duration_seconds: 78.78 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-neend_female_2_hi.mp3", duration_seconds: 82.97 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-neend_female_3_hi.mp3", duration_seconds: 89.38 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-neend_male_1_hi.mp3", duration_seconds: 79.9 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-neend_male_2_hi.mp3", duration_seconds: 77.7 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-neend_male_3_hi.mp3", duration_seconds: 81.91 },
      ],
    },
    {
      id: "seed-bahadur-jugnu",
      type: "story",
      title: "Bahadur Chhota Jugnu",
      description: "Ek chhota sa jugnu bhule hue jaanwaron ko ghar ka raasta dikhata hai.",
      cover: COVERS.braveFirefly,
      text: "Gungunate Jungle ke beech mein ek chhota sa jugnu rehta tha jiska naam tha Flicker. Baaki jugnuon ki tarah uski roshni chamakdaar nahi thi \u2014 bilkul ek chhoti si mombatti jaisi.\n\nLekin usi raat, ek chhota khargosh Clover jungle ke sabse andhere hisse mein kho gaya. \"Meri roshni ke peeche aao!\" Flicker ne kaha. Roshni chhoti thi, lekin Clover ko har kadam dikhane ke liye kaafi thi.\n\nSaath mein chale, Flicker raasta dikhata raha, jab tak Clover apne ghar nahi pahunch gaya jahan Mamma Rabbit intezaar kar rahi thi.\n\n\"Shukriya, chhoti roshni,\" Clover ne unghaate hue kaha. \"Tum pure jungle ke sabse bahadur jugnu ho.\"\n\nAur us raat ke baad, Flicker ne kabhi khud ko chhota nahi samjha. Kyunki chhoti si roshni bhi kisi ko ghar pahuncha sakti hai.",
      target_age: 5,
      duration: 4,
      like_count: 92,
      save_count: 16,
      view_count: 191,
      categories: ["Janwar", "Sahas", "Dosti"],
      theme: "adventure",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-bahad_female_1_hi.mp3", duration_seconds: 81.3 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-bahad_female_2_hi.mp3", duration_seconds: 84.43 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-bahad_female_3_hi.mp3", duration_seconds: 91.84 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-bahad_male_1_hi.mp3", duration_seconds: 96.54 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-bahad_male_2_hi.mp3", duration_seconds: 98.5 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-bahad_male_3_hi.mp3", duration_seconds: 87.59 },
      ],
    },
    {
      id: "seed-chaand-ki-lori",
      type: "story",
      title: "Chaand ki Lori",
      description: "Chaand apni meethi lori se sabhi jaanwaron ko sulata hai.",
      cover: COVERS.moonLullaby,
      text: "Jab suraj pahaadiyon ke peeche chala gaya, Chaand dheere-dheere uthha aur Willow Meadow pe chandi ki roshni bikher di.\n\n\"Chup ho ja, chhoti lomdi,\" Chaand ne gaaya, aur lomdi apni khoh mein simat gayi.\n\n\"So ja, chhote ullu,\" Chaand ne gungunaya, aur ullu ne apna sar apne pankh ke neeche chhupa liya.\n\nPhir Chaand ne tumhari taraf dekha aur sabse meetha sur gaaya: \"Shubh raatri, mere chhote sapne dekhne waale. Subah tak taare tumhara khayal rakhenge.\"\n\nAur bas phir, poori duniya sukoon se so gayi.",
      target_age: 3,
      duration: 3,
      like_count: 99,
      save_count: 10,
      view_count: 427,
      categories: ["Lori", "Janwar", "Prakriti"],
      theme: "fairy_tale",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-chaan_female_1_hi.mp3", duration_seconds: 54.44 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-chaan_female_2_hi.mp3", duration_seconds: 55.57 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-chaan_female_3_hi.mp3", duration_seconds: 52.87 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-chaan_male_1_hi.mp3", duration_seconds: 58.12 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-chaan_male_2_hi.mp3", duration_seconds: 55.46 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-chaan_male_3_hi.mp3", duration_seconds: 52.56 },
      ],
    },
    {
      id: "seed-captain-sitaara",
      type: "story",
      title: "Captain Sitaara aur Dhumketu ki Race",
      description: "Ek space explorer dhumketu se race lagati hai birthday wish dene ke liye.",
      cover: COVERS.captainStardust,
      text: "Captain Sitaara ne apna chamakdar helmet theek kiya aur apne starship Silver Dreamer ka control pakda. Aaj ki mission sabse zaroori thi \u2014 Planet Cakealot pe birthday wish pahunchana, aadhi raat se pehle!\n\nSilver Dreamer Saturn ke chhalon ke beech se nikli, asteroid field ko dodge kiya, aur ek neele dhumketu Flash ke saath race lagayi.\n\nWo bilkul sahi waqt pe pahunchi! Captain Sitaara ne wish deliver ki \u2014 ek chamakta sona sitaara.\n\n\"Mission poora hua,\" usne muskuraate hue kaha. \"Ab ghar chalein. Space explorers ko bhi neend aati hai.\"\n\nAur jab Silver Dreamer shaant aasmaan se ghar laut rahi thi, taaron ne bhi apni roshni dheemi ki aur shubh raatri kahi.",
      target_age: 7,
      duration: 4,
      like_count: 109,
      save_count: 84,
      view_count: 394,
      categories: ["Antariksh", "Sahas"],
      theme: "space",
      musicProfile: "cosmic-voyage",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-capta_female_1_hi.mp3", duration_seconds: 74.63 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-capta_female_2_hi.mp3", duration_seconds: 73.6 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-capta_female_3_hi.mp3", duration_seconds: 75.61 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-capta_male_1_hi.mp3", duration_seconds: 75.74 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-capta_male_2_hi.mp3", duration_seconds: 76.73 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-capta_male_3_hi.mp3", duration_seconds: 67.25 },
      ],
    },
    {
      id: "seed-gungunata-baag",
      type: "story",
      title: "Gungunata Baag",
      description: "Ek jaadui baag jahan phool kahaniyan sunate hain.",
      cover: COVERS.gardenWhispers,
      text: "Daadi ke ghar ke peeche, Maya ko ek aisa baag mila jo sone ki roshni se chamak raha tha. Yahan ke phool jaadui the \u2014 gulaab jo lantern ki tarah chamakte the, lily jo dhun gaati thi.\n\nHar phool ke paas ek alag kahani thi. Daisy chuhon ki bahaduri ki kahani sunati thi. Tulip meherbaani ki puraani kathayein batati thi. Lavender chaandni raaton ki kavitayein sunata tha.\n\nHar kahani aise khatam hoti thi: \"Ab aankhein band karo, pyaare. Kal ek aur kahani tumhara intezaar kar rahi hogi.\"",
      target_age: 8,
      duration: 5,
      like_count: 181,
      save_count: 36,
      view_count: 129,
      categories: ["Jaadui", "Kalpana", "Prakriti"],
      theme: "fantasy",
      musicProfile: "enchanted-garden",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-gungu_female_1_hi.mp3", duration_seconds: 62.02 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-gungu_female_2_hi.mp3", duration_seconds: 66.75 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-gungu_female_3_hi.mp3", duration_seconds: 75.93 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-gungu_male_1_hi.mp3", duration_seconds: 66.11 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-gungu_male_2_hi.mp3", duration_seconds: 77.39 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-gungu_male_3_hi.mp3", duration_seconds: 63.38 },
      ],
    },
    {
      id: "seed-chamakta-sapna",
      type: "poem",
      title: "Chamakta Sapna",
      description: "Taaron ki nigrani mein sone ki meethi kavita.",
      cover: COVERS.twinkleDream,
      text: "Taare jhilmil karte hain aasmaan mein,\nTumhare sapne basate hain unki chaan mein.\nChaanda muskuraye gol chamakdaar,\nChaandi mein lapet le saara sansaar.\n\nAankhein moondo ab, mere pyaare taare,\nRaat aayi hai, jag uthe sitaare.\nKal subah suraj naya aayega,\nPar ab sapnon ka jahan le jaayega.",
      target_age: 3,
      duration: 2,
      like_count: 27,
      save_count: 82,
      view_count: 386,
      categories: ["Lori", "Jaadui"],
      theme: "dreamy",
      musicProfile: "starlight-lullaby",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-chama_female_1_hi.mp3", duration_seconds: 26.78 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-chama_female_2_hi.mp3", duration_seconds: 28.61 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-chama_female_3_hi.mp3", duration_seconds: 30.07 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-chama_male_1_hi.mp3", duration_seconds: 30.93 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-chama_male_2_hi.mp3", duration_seconds: 30.22 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-chama_male_3_hi.mp3", duration_seconds: 27.48 },
      ],
    },
    {
      id: "seed-ullu-ki-shubhraatri",
      type: "poem",
      title: "Ullu ki Shubh Raatri",
      description: "Ek samajhdaar ullu jungle ke har praani ko shubh raatri kehta hai.",
      cover: COVERS.owlGoodnight,
      text: "Uhoo-uhoo, ullu bole budhe pedh se,\nShubh raatri machli ko neeli nadiya ke desh se.\nShubh raatri khargosh ko garm bistar mein,\nShubh raatri ladybug ko phoolon ke ghar mein.\n\nUhoo-uhoo, lomdi so ja apni khoh mein,\nBatakh aur murgi bhi sapnon ki choh mein.\nShubh raatri gilahri ko meethi neend aaye,\nUhoo-uhoo, mere bachche \u2014 ab chain se so jaaye.",
      target_age: 2,
      duration: 2,
      like_count: 133,
      save_count: 60,
      view_count: 200,
      categories: ["Janwar", "Lori"],
      theme: "animals",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-ullu-_female_1_hi.mp3", duration_seconds: 30.41 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-ullu-_female_2_hi.mp3", duration_seconds: 28.12 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-ullu-_female_3_hi.mp3", duration_seconds: 33.86 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-ullu-_male_1_hi.mp3", duration_seconds: 28.49 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-ullu-_male_2_hi.mp3", duration_seconds: 33.13 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-ullu-_male_3_hi.mp3", duration_seconds: 29.96 },
      ],
    },
    {
      id: "seed-sapnon-ki-naav",
      type: "song",
      title: "Sapnon ki Naav",
      description: "Chaandni raat mein sapnon ke desh ki taraf le jaane wala gaana.",
      cover: COVERS.sailingDreamland,
      text: "[Verse 1]\nChandi ki naav pe hum sawaar chalein,\nChaandni samundar ke paar chalein.\nTaare gaate hain lori meethi pyaari,\nLe chalein sapnon ki phulajhaari.\n\n[Chorus]\nSapnon ka desh, sapnon ka desh, aao chalein,\nBaigani aasmaan mein udte chalein.\nSapnon ka desh, sapnon ka desh, raat suhaani,\nChintaon ko bhool jaao, suno yeh kahaani.",
      target_age: 4,
      duration: 2,
      like_count: 20,
      save_count: 25,
      view_count: 285,
      categories: ["Lori", "Jaadui"],
      theme: "dreamy",
      musicProfile: "ocean-drift",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-sapno_female_1_hi.mp3", duration_seconds: 26.28 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-sapno_female_2_hi.mp3", duration_seconds: 28.43 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-sapno_female_3_hi.mp3", duration_seconds: 27.57 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-sapno_male_1_hi.mp3", duration_seconds: 26.48 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-sapno_male_2_hi.mp3", duration_seconds: 20.14 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-sapno_male_3_hi.mp3", duration_seconds: 25.48 },
      ],
    },
  ],
};

/** Helper to get stories for current language */
export function getStories(lang = 'en') {
  return SEED_STORIES[lang] || SEED_STORIES.en;
}
