/**
 * Fallback seed data for when the backend is unreachable.
 * English + Hindi versions keyed by language.
 * Cover images are local SVG illustrations with consistent mystical/dreamy style.
 */

// Cover images — mystical dreamy SVG illustrations in /public/covers/
const COVERS = {
  sleepyCloud: '/covers/sleepy-cloud.svg',
  braveFirefly: '/covers/brave-firefly.svg',
  moonLullaby: '/covers/moon-lullaby.svg',
  captainStardust: '/covers/captain-stardust.svg',
  gardenWhispers: '/covers/garden-whispers.svg',
  twinkleDream: '/covers/twinkle-dream.svg',
  owlGoodnight: '/covers/owl-goodnight.svg',
  sailingDreamland: '/covers/sailing-dreamland.svg',
};

export const SEED_STORIES = {
  en: [
    {
      id: "seed-sleepy-cloud",
      type: "story",
      title: "The Sleepy Cloud",
      description: "A fluffy cloud drifts across the moonlit sky, collecting dreams for sleepy children.",
      cover: COVERS.sleepyCloud,
      text: "High above the rooftops, a fluffy little cloud named Nimbus floated gently through the night sky. Nimbus had the most important job in all the world \u2014 collecting sweet dreams from the stars and sprinkling them over sleeping children.\n\nTonight, the stars were especially sparkly. Nimbus reached out with soft, cottony arms and caught a dream about flying horses, another about a garden made entirely of candy, and one more about a friendly dragon who loved to share warm hugs.\n\nAs Nimbus drifted over your house, it gently shook its fluffy body, and the dreams floated down like tiny snowflakes. They landed softly on your pillow, waiting for you to close your eyes.\n\n\"Sweet dreams, little one,\" whispered Nimbus, as it continued its journey across the peaceful night sky, leaving a trail of starlight behind.",
      target_age: 4,
      duration: 3,
      like_count: 57,
      save_count: 88,
      view_count: 160,
      categories: ["Fantasy", "Lullabies", "Magical"],
      theme: "dreamy",
      musicProfile: "dreamy-clouds",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/7fe248e1_female_1.mp3", duration_seconds: 83.68 },
        { voice: "female_2", url: "/audio/pre-gen/7fe248e1_female_2.mp3", duration_seconds: 74.94 },
        { voice: "female_3", url: "/audio/pre-gen/7fe248e1_female_3.mp3", duration_seconds: 68.6 },
        { voice: "asmr", url: "/audio/pre-gen/7fe248e1_asmr.mp3", duration_seconds: 73.96 },
        { voice: "male_1", url: "/audio/pre-gen/7fe248e1_male_1.mp3", duration_seconds: 64.78 },
        { voice: "male_2", url: "/audio/pre-gen/7fe248e1_male_2.mp3", duration_seconds: 68.33 },
        { voice: "male_3", url: "/audio/pre-gen/7fe248e1_male_3.mp3", duration_seconds: 69.11 },
      ],
    },
    {
      id: "seed-brave-firefly",
      type: "story",
      title: "The Brave Little Firefly",
      description: "A tiny firefly discovers its light can guide lost animals home.",
      cover: COVERS.braveFirefly,
      text: "In the heart of Whispering Woods lived a tiny firefly named Flicker. Unlike the other fireflies who shone brilliant gold, Flicker\u2019s light was small and soft.\n\nBut that very night, a baby rabbit named Clover got lost in the darkest part of the forest. \"Follow my light!\" said Flicker. And though the glow was small, it was just enough for Clover to see each step of the way.\n\nTogether, they walked through the forest, Flicker lighting the path one step at a time, until they reached Clover\u2019s burrow where Mama Rabbit was waiting.\n\n\"Thank you, little light,\" said Clover. \"You're the bravest firefly in all the woods.\"\n\nAnd from that night on, Flicker never felt small again. Because even the tiniest light can guide someone home.",
      target_age: 5,
      duration: 4,
      like_count: 92,
      save_count: 16,
      view_count: 191,
      categories: ["Animals", "Adventure", "Friendship"],
      theme: "adventure",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/8e516449_female_1.mp3", duration_seconds: 112.79 },
        { voice: "female_2", url: "/audio/pre-gen/8e516449_female_2.mp3", duration_seconds: 105.24 },
        { voice: "female_3", url: "/audio/pre-gen/8e516449_female_3.mp3", duration_seconds: 94.19 },
        { voice: "asmr", url: "/audio/pre-gen/8e516449_asmr.mp3", duration_seconds: 106.47 },
        { voice: "male_1", url: "/audio/pre-gen/8e516449_male_1.mp3", duration_seconds: 88.94 },
        { voice: "male_2", url: "/audio/pre-gen/8e516449_male_2.mp3", duration_seconds: 72.64 },
        { voice: "male_3", url: "/audio/pre-gen/8e516449_male_3.mp3", duration_seconds: 73.16 },
      ],
    },
    {
      id: "seed-moons-lullaby",
      type: "story",
      title: "The Moon's Lullaby",
      description: "The Moon sings a gentle song to help all the animals fall asleep.",
      cover: COVERS.moonLullaby,
      text: "When the sun tucked itself behind the hills, the Moon rose slowly, casting a soft silver glow over Willow Meadow.\n\n\"Hush now, little fox,\" the Moon sang softly, and the fox curled up in its cozy den.\n\n\"Rest now, little owl,\" the Moon hummed, and the owl tucked its head under its wing.\n\nAnd then the Moon looked down at you and sang the sweetest note of all: \"Goodnight, my little dreamer. The stars will watch over you until morning comes.\"\n\nAnd with that, the whole world fell into a peaceful, happy sleep.",
      target_age: 3,
      duration: 3,
      like_count: 99,
      save_count: 10,
      view_count: 427,
      categories: ["Lullabies", "Animals", "Nature"],
      theme: "fairy_tale",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/30dec3e8_female_1.mp3", duration_seconds: 110.94 },
        { voice: "female_2", url: "/audio/pre-gen/30dec3e8_female_2.mp3", duration_seconds: 96.84 },
        { voice: "female_3", url: "/audio/pre-gen/30dec3e8_female_3.mp3", duration_seconds: 86.4 },
        { voice: "asmr", url: "/audio/pre-gen/30dec3e8_asmr.mp3", duration_seconds: 94.89 },
        { voice: "male_1", url: "/audio/pre-gen/30dec3e8_male_1.mp3", duration_seconds: 81.85 },
        { voice: "male_2", url: "/audio/pre-gen/30dec3e8_male_2.mp3", duration_seconds: 85.9 },
        { voice: "male_3", url: "/audio/pre-gen/30dec3e8_male_3.mp3", duration_seconds: 82.25 },
      ],
    },
    {
      id: "seed-captain-stardust",
      type: "story",
      title: "Captain Stardust and the Comet Race",
      description: "A space explorer races comets to deliver a birthday wish.",
      cover: COVERS.captainStardust,
      text: "Captain Stardust adjusted her sparkly helmet and gripped the controls of her starship, the Silver Dreamer. Tonight\u2019s mission \u2014 deliver a birthday wish to Planet Cakealot before midnight!\n\nThe Silver Dreamer zoomed past Saturn\u2019s rings, weaved through an asteroid field, and raced alongside a brilliant blue comet named Flash.\n\nThey arrived just in time! Captain Stardust delivered the wish \u2014 a glowing golden star.\n\n\"Mission complete,\" she smiled. \"Even space explorers need their sleep.\"\n\nAnd as the Silver Dreamer sailed home, the stars whispered goodnight.",
      target_age: 7,
      duration: 4,
      like_count: 109,
      save_count: 84,
      view_count: 394,
      categories: ["Space", "Adventure"],
      theme: "space",
      musicProfile: "cosmic-voyage",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/d73e9530_female_1.mp3", duration_seconds: 128.4 },
        { voice: "female_2", url: "/audio/pre-gen/d73e9530_female_2.mp3", duration_seconds: 123.99 },
        { voice: "female_3", url: "/audio/pre-gen/d73e9530_female_3.mp3", duration_seconds: 106.21 },
        { voice: "asmr", url: "/audio/pre-gen/d73e9530_asmr.mp3", duration_seconds: 115.65 },
        { voice: "male_1", url: "/audio/pre-gen/d73e9530_male_1.mp3", duration_seconds: 106.39 },
        { voice: "male_2", url: "/audio/pre-gen/d73e9530_male_2.mp3", duration_seconds: 104.89 },
        { voice: "male_3", url: "/audio/pre-gen/d73e9530_male_3.mp3", duration_seconds: 106.83 },
      ],
    },
    {
      id: "seed-garden-whispers",
      type: "story",
      title: "The Garden of Whispers",
      description: "A magical garden where flowers tell stories to anyone who listens.",
      cover: COVERS.gardenWhispers,
      text: "Behind Grandmother\u2019s house, Maya found a garden that shimmered with golden light. The flowers were magical \u2014 roses that glowed like lanterns, lilies that hummed melodies.\n\nEach flower held a different story. The daisies told tales of brave mice. The tulips shared legends of kindness. The lavender whispered poems about starlit nights.\n\nEvery story ended the same way: \"Close your eyes now, dear listener. Tomorrow, there will be another story waiting just for you.\"",
      target_age: 8,
      duration: 5,
      like_count: 181,
      save_count: 36,
      view_count: 129,
      categories: ["Magical", "Fantasy", "Nature"],
      theme: "fantasy",
      musicProfile: "enchanted-garden",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/9fba7605_female_1.mp3", duration_seconds: 144.92 },
        { voice: "female_2", url: "/audio/pre-gen/9fba7605_female_2.mp3", duration_seconds: 130.24 },
        { voice: "female_3", url: "/audio/pre-gen/9fba7605_female_3.mp3", duration_seconds: 113.83 },
        { voice: "asmr", url: "/audio/pre-gen/9fba7605_asmr.mp3", duration_seconds: 138.25 },
        { voice: "male_1", url: "/audio/pre-gen/9fba7605_male_1.mp3", duration_seconds: 113.14 },
        { voice: "male_2", url: "/audio/pre-gen/9fba7605_male_2.mp3", duration_seconds: 113.14 },
        { voice: "male_3", url: "/audio/pre-gen/9fba7605_male_3.mp3", duration_seconds: 113.73 },
      ],
    },
    {
      id: "seed-twinkle-dream",
      type: "poem",
      title: "Twinkle Dream",
      description: "A gentle bedtime poem about stars watching over sleeping children.",
      cover: COVERS.twinkleDream,
      text: "The stars above are blinking bright,\nThey guard your dreams throughout the night.\nThe moon is smiling, round and white,\nAnd wraps the world in silver light.\n\nSo close your eyes, my little one,\nThe day is done, the night\u2019s begun.\nTomorrow brings a brand new sun,\nBut now it\u2019s time for sleep and fun.",
      target_age: 3,
      duration: 2,
      like_count: 27,
      save_count: 82,
      view_count: 386,
      categories: ["Lullabies", "Magical"],
      theme: "dreamy",
      musicProfile: "starlight-lullaby",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/c8796852_female_1.mp3", duration_seconds: 52.02 },
        { voice: "female_2", url: "/audio/pre-gen/c8796852_female_2.mp3", duration_seconds: 39.73 },
        { voice: "female_3", url: "/audio/pre-gen/c8796852_female_3.mp3", duration_seconds: 36.73 },
        { voice: "asmr", url: "/audio/pre-gen/c8796852_asmr.mp3", duration_seconds: 42.63 },
        { voice: "male_1", url: "/audio/pre-gen/c8796852_male_1.mp3", duration_seconds: 36.94 },
        { voice: "male_2", url: "/audio/pre-gen/c8796852_male_2.mp3", duration_seconds: 39.81 },
        { voice: "male_3", url: "/audio/pre-gen/c8796852_male_3.mp3", duration_seconds: 35.77 },
      ],
    },
    {
      id: "seed-owls-goodnight",
      type: "poem",
      title: "The Owl's Goodnight",
      description: "A wise owl says goodnight to every creature in the forest.",
      cover: COVERS.owlGoodnight,
      text: "Hoo-hoo, says the owl from the old oak tree,\nGoodnight to the fish in the deep blue sea.\nGoodnight to the rabbits in burrows so snug,\nGoodnight to the ladybug under the rug.\n\nHoo-hoo, says the owl to the fox in its den,\nTo the duck and the drake and the little brown hen.\nGoodnight to the squirrel with acorns to keep,\nHoo-hoo, little darling \u2014 it\u2019s time now to sleep.",
      target_age: 2,
      duration: 2,
      like_count: 133,
      save_count: 60,
      view_count: 200,
      categories: ["Animals", "Lullabies"],
      theme: "animals",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/e32eaee0_female_1.mp3", duration_seconds: 51.48 },
        { voice: "female_2", url: "/audio/pre-gen/e32eaee0_female_2.mp3", duration_seconds: 33.1 },
        { voice: "female_3", url: "/audio/pre-gen/e32eaee0_female_3.mp3", duration_seconds: 30.88 },
        { voice: "asmr", url: "/audio/pre-gen/e32eaee0_asmr.mp3", duration_seconds: 35.29 },
        { voice: "male_1", url: "/audio/pre-gen/e32eaee0_male_1.mp3", duration_seconds: 30.65 },
        { voice: "male_2", url: "/audio/pre-gen/e32eaee0_male_2.mp3", duration_seconds: 30.03 },
        { voice: "male_3", url: "/audio/pre-gen/e32eaee0_male_3.mp3", duration_seconds: 31.87 },
      ],
    },
    {
      id: "seed-sailing-dreamland",
      type: "song",
      title: "Sailing to Dreamland",
      description: "A gentle lullaby about sailing to the land of dreams.",
      cover: COVERS.sailingDreamland,
      text: "[Verse 1]\nWe\u2019re sailing on a silver boat,\nAcross the moonlit sea.\nThe stars are singing lullabies,\nFor you and me.\n\n[Chorus]\nDreamland, dreamland, just close your eyes,\nSail away under purple skies.\nDreamland, dreamland, the night is kind,\nLeave all your worries far behind.",
      target_age: 4,
      duration: 2,
      like_count: 20,
      save_count: 25,
      view_count: 285,
      categories: ["Lullabies", "Magical"],
      theme: "dreamy",
      musicProfile: "ocean-drift",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/a3945b7b_female_1.mp3", duration_seconds: 64.3 },
        { voice: "female_2", url: "/audio/pre-gen/a3945b7b_female_2.mp3", duration_seconds: 57.04 },
        { voice: "female_3", url: "/audio/pre-gen/a3945b7b_female_3.mp3", duration_seconds: 45.81 },
        { voice: "asmr", url: "/audio/pre-gen/a3945b7b_asmr.mp3", duration_seconds: 50.82 },
        { voice: "male_1", url: "/audio/pre-gen/a3945b7b_male_1.mp3", duration_seconds: 44.04 },
        { voice: "male_2", url: "/audio/pre-gen/a3945b7b_male_2.mp3", duration_seconds: 45.8 },
        { voice: "male_3", url: "/audio/pre-gen/a3945b7b_male_3.mp3", duration_seconds: 46.18 },
      ],
    },
    {
      id: "gen-6e675d15e1f5",
      type: "story",
      title: "Moonbeam's Ocean Friend",
      description: "A gentle moonbeam discovers friendship with sea waves in a futuristic underwater world.",
      cover: "/covers/moonbeam-ocean.svg",
      text: "Moonbeam shines down, down, down.  Into future ocean deep. Glowing fish swim by, by, by.  Wave says 'Hello friend!'  Moonbeam giggles soft and bright.  'Sleep now, ocean friend.'  Together they rest, rest, rest.",
      target_age: 0,
      duration: 1,
      like_count: 97,
      save_count: 31,
      view_count: 287,
      categories: ["Ocean", "Friendship", "Bedtime"],
      theme: "ocean",
      musicProfile: "ocean-drift",
      audio_variants: [
        { voice: "male_1", url: "/audio/pre-gen/gen-6e67_male_1.mp3", duration_seconds: 19.68 },
        { voice: "female_3", url: "/audio/pre-gen/gen-6e67_female_3.mp3", duration_seconds: 21.23 },
        { voice: "female_1", url: "/audio/pre-gen/gen-6e67_female_1.mp3", duration_seconds: 29.4 },
        { voice: "female_2", url: "/audio/pre-gen/gen-6e67_female_2.mp3", duration_seconds: 23.26 },
        { voice: "male_3", url: "/audio/pre-gen/gen-6e67_male_3.mp3", duration_seconds: 19.06 },
        { voice: "male_2", url: "/audio/pre-gen/gen-6e67_male_2.mp3", duration_seconds: 19.75 },
        { voice: "asmr", url: "/audio/pre-gen/gen-6e67_asmr.mp3", duration_seconds: 23.66 },
      ],
    },
    {
      id: "gen-3de58fd2aa2d",
      type: "story",
      title: "Bella's Soft Petal Bed",
      description: "A gentle butterfly finds the perfect flower to rest in as night falls over the magical garden.",
      cover: "/covers/petal-bed.svg",
      text: "Bella butterfly flies, flies, flies.  Pretty flowers dance, dance, dance.  Which flower bed? Which flower bed?  Soft rose petals, warm and red.  Hush, hush, little wings.  Moonbeams sing sweet lullabies.  Close tiny eyes, sleep tight. Sweet dreams in flower light.",
      target_age: 0,
      duration: 1,
      like_count: 47,
      save_count: 11,
      view_count: 71,
      categories: ["Nature", "Sleep", "Fantasy"],
      theme: "nature",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/gen-3de5_female_1.mp3", duration_seconds: 34.12 },
        { voice: "female_3", url: "/audio/pre-gen/gen-3de5_female_3.mp3", duration_seconds: 28.1 },
        { voice: "female_2", url: "/audio/pre-gen/gen-3de5_female_2.mp3", duration_seconds: 30.18 },
        { voice: "male_2", url: "/audio/pre-gen/gen-3de5_male_2.mp3", duration_seconds: 23.71 },
        { voice: "male_1", url: "/audio/pre-gen/gen-3de5_male_1.mp3", duration_seconds: 25.61 },
        { voice: "male_3", url: "/audio/pre-gen/gen-3de5_male_3.mp3", duration_seconds: 25.62 },
        { voice: "asmr", url: "/audio/pre-gen/gen-3de5_asmr.mp3", duration_seconds: 27.65 },
      ],
    },
    {
      id: "gen-4f3ff03979dc",
      type: "poem",
      title: "Arjun's Flying Robot Friend",
      description: "A brave little boy in futuristic India discovers a magical robot friend who teaches him about play and friendship through floating adventures.",
      cover: "/covers/flying-robot.svg",
      text: "Little Arjun found a robot friend,\nShiny blue with lights that bend.\n\nRobot says, \"Let's float and play!\"\nUp they go, hooray, hooray!\n\nThrough the sky above Mumbai,\nFriends together, flying high.\n\nRobot whispers, \"Time to rest,\nFriendship is the very best.\"\n\nDown they float to bed so deep,\nArjun smiles and falls asleep.",
      target_age: 2,
      duration: 1,
      like_count: 77,
      save_count: 18,
      view_count: 146,
      categories: ["Fantasy", "Friendship", "Futuristic", "Bedtime"],
      theme: "fantasy",
      musicProfile: "enchanted-garden",
      audio_variants: [
        { voice: "female_2", url: "/audio/pre-gen/gen-4f3f_female_2.mp3", duration_seconds: 42.2 },
        { voice: "female_1", url: "/audio/pre-gen/gen-4f3f_female_1.mp3", duration_seconds: 51.71 },
        { voice: "male_1", url: "/audio/pre-gen/gen-4f3f_male_1.mp3", duration_seconds: 35.62 },
        { voice: "female_3", url: "/audio/pre-gen/gen-4f3f_female_3.mp3", duration_seconds: 37.69 },
        { voice: "male_2", url: "/audio/pre-gen/gen-4f3f_male_2.mp3", duration_seconds: 35.9 },
        { voice: "asmr", url: "/audio/pre-gen/gen-4f3f_asmr.mp3", duration_seconds: 44.51 },
        { voice: "male_3", url: "/audio/pre-gen/gen-4f3f_male_3.mp3", duration_seconds: 35.78 },
      ],
    },
    {
      id: "gen-a67cde9762b6",
      type: "poem",
      title: "Pepper's Garden Light",
      description: "A gentle ladybug named Pepper helps her vegetable garden family by finding the perfect nighttime glow. A soothing poem about problem-solving and caring for home.",
      cover: "/covers/garden-light.svg",
      text: "Little Pepper, red and round,\nIn the garden, safe and sound.\n\nCarrots sleepy, peas so tired,\nAll the veggies feeling wired.\n\nPepper thinks, \"What can I do?\nMake them cozy, through and through.\"\n\nFound a firefly's gentle gleam,\nSoft and warm, a golden dream.\n\nNow the garden glows so bright,\nEveryone says, \"Good night, good night.\"\n\nPepper curls upon a leaf,\nGarden home brings sweet relief.",
      target_age: 2,
      duration: 1,
      like_count: 13,
      save_count: 31,
      view_count: 215,
      categories: ["Problem Solving", "Family", "Nature"],
      theme: "bedtime",
      musicProfile: "starlight-lullaby",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/gen-a67c_female_1.mp3", duration_seconds: 60.78 },
        { voice: "female_2", url: "/audio/pre-gen/gen-a67c_female_2.mp3", duration_seconds: 52.93 },
        { voice: "female_3", url: "/audio/pre-gen/gen-a67c_female_3.mp3", duration_seconds: 48.85 },
        { voice: "male_1", url: "/audio/pre-gen/gen-a67c_male_1.mp3", duration_seconds: 43.52 },
        { voice: "male_2", url: "/audio/pre-gen/gen-a67c_male_2.mp3", duration_seconds: 45.41 },
        { voice: "male_3", url: "/audio/pre-gen/gen-a67c_male_3.mp3", duration_seconds: 48.63 },
        { voice: "asmr", url: "/audio/pre-gen/gen-a67c_asmr.mp3", duration_seconds: 52.55 },
      ],
    },
    {
      id: "gen-a8a2146a4f36",
      type: "poem",
      title: "The Forest's Digital Symphony",
      description: "A young fox and her woodland friends discover an ancient grove where nature and technology harmonize, teaching them that modern passions can coexist beautifully with the natural world.",
      cover: "/covers/digital-forest.svg",
      text: "In the heart of the Pacific Northwest,\nWhere cedars touch the clouded sky,\nLive creatures with a modern quest—\nTo blend old wisdom with WiFi.\n\nLuna the fox codes by moonlight,\nWhile Sage the owl debugs her dreams,\nAnd River the raccoon streams midnight\nNature documentaries by streams.\n\nTogether they seek the Digital Grove,\nWhere legend says the ancients planned\nA place where circuits learn to love\nThe rhythm of the living land.\n\nThrough fern-filled paths and mossy stones,\nThey follow signals in the breeze,\nUntil they find where nature owns\nThe harmony of code and trees.\n\nHere algorithms dance with rain,\nAnd servers hum like cricket songs,\nProof that progress need not stain\nThe world where every heart belongs.\n\nSo rest now, knowing dreams can weave\nTechnology with nature's art,\nAnd every passion we believe\nCan honor both the mind and heart.",
      target_age: 13,
      duration: 2,
      like_count: 68,
      save_count: 45,
      view_count: 95,
      categories: ["Nature", "Technology", "Friendship", "Adventure", "Environmental Awareness"],
      theme: "nature",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_2", url: "/audio/pre-gen/gen-a8a2_female_2.mp3", duration_seconds: 91.27 },
        { voice: "female_1", url: "/audio/pre-gen/gen-a8a2_female_1.mp3", duration_seconds: 109.14 },
        { voice: "male_1", url: "/audio/pre-gen/gen-a8a2_male_1.mp3", duration_seconds: 77.32 },
        { voice: "female_3", url: "/audio/pre-gen/gen-a8a2_female_3.mp3", duration_seconds: 87.05 },
        { voice: "male_2", url: "/audio/pre-gen/gen-a8a2_male_2.mp3", duration_seconds: 85.55 },
        { voice: "male_3", url: "/audio/pre-gen/gen-a8a2_male_3.mp3", duration_seconds: 87.55 },
        { voice: "asmr", url: "/audio/pre-gen/gen-a8a2_asmr.mp3", duration_seconds: 96.34 },
      ],
    },
    {
      id: "gen-9e44d4374d44",
      type: "poem",
      title: "Amara and the Star-Song Celebration",
      description: "A young prehistoric astronomer in ancient Africa discovers her unique gift for reading celestial patterns and leads her tribe in a celebration of the cosmos.",
      cover: "/covers/star-celebration.svg",
      text: "In the cradle of humanity's dawn,\nWhere acacia trees stretched toward the sky,\nLived Amara, whose eyes were drawn\nTo the ancient stars wheeling by.\n\nHer grandmother spoke of stellar lore,\nHow constellations told the seasons' tale,\nBut Amara saw patterns no one saw before—\nCelestial rhythms that never fail.\n\nShe traced the paths of wandering lights,\nThose planets dancing their orbital song,\nCalculating distances through countless nights,\nWondering where in this dance she belonged.\n\nThe elders gathered when she shared her sight,\nHow Venus rises before the dawn,\nHow Jupiter's moons eclipse its light,\nHow stellar wisdom can guide us on.\n\n\"You are the keeper of cosmic truth,\"\nHer grandmother smiled with ancient grace,\n\"Your gift connects our people's youth\nTo the infinite wisdom of time and space.\"\n\nThe tribe prepared a celebration grand,\nWith drums that echoed the pulsar's beat,\nAnd Amara, with her steady hand,\nMade star-maps where science and spirit meet.\n\nAs firelight danced beneath the dome\nOf countless suns in velvet night,\nAmara knew she'd found her home—\nA bridge between earth's warmth and stellar light.\n\nNow when you gaze at stars above,\nRemember Amara's gift so true:\nThat science blooms from wonder's love,\nAnd the cosmos celebrates in you.",
      target_age: 13,
      duration: 2,
      like_count: 49,
      save_count: 15,
      view_count: 245,
      categories: ["Science", "Self-Discovery", "Cultural Celebration", "Astronomy"],
      theme: "science",
      musicProfile: "cosmic-voyage",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/gen-9e44_female_1.mp3", duration_seconds: 151.5 },
        { voice: "female_3", url: "/audio/pre-gen/gen-9e44_female_3.mp3", duration_seconds: 120.89 },
        { voice: "female_2", url: "/audio/pre-gen/gen-9e44_female_2.mp3", duration_seconds: 131.06 },
        { voice: "male_1", url: "/audio/pre-gen/gen-9e44_male_1.mp3", duration_seconds: 113.38 },
        { voice: "male_2", url: "/audio/pre-gen/gen-9e44_male_2.mp3", duration_seconds: 114.02 },
        { voice: "male_3", url: "/audio/pre-gen/gen-9e44_male_3.mp3", duration_seconds: 118.61 },
        { voice: "asmr", url: "/audio/pre-gen/gen-9e44_asmr.mp3", duration_seconds: 128.34 },
      ],
    },
    {
      id: "gen-b8847383ab32",
      type: "poem",
      title: "Nayeli's Arctic School Discovery",
      description: "A brave Inuit girl discovers a magical ice school where polar animals gather to learn together in the snowy wilderness.",
      cover: "/covers/arctic-school.svg",
      text: "Long ago in the Arctic white,\nLived Nayeli, brave and bright.\nWith her sealskin boots so warm,\nShe walked through each snowy storm.\n\nOne day while hunting for her meal,\nShe found tracks that looked so real.\nPolar bear paws in the snow,\nWhere could they possibly go?\n\nFollowing prints both big and small,\nShe climbed up an icy wall.\nThere behind the frozen peak,\nShe found what she came to seek.\n\nA school made of crystal ice,\nWhere animals learned so nice!\nBear cubs counting fish to eat,\nSeals learning to swim so neat.\n\nArctic foxes shared their food,\nWhile walruses played and wooed.\nNayeli watched with wonder deep,\nAs creatures learned before they sleep.\n\nNow when stars begin to glow,\nShe dreams of that school of snow.\nWhere all creatures, big and small,\nLearn together, one and all.",
      target_age: 4,
      duration: 1,
      like_count: 43,
      save_count: 21,
      view_count: 74,
      categories: ["Arctic Adventure", "Animal Friends", "Discovery", "Learning"],
      theme: "animals",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_2", url: "/audio/pre-gen/gen-b884_female_2.mp3", duration_seconds: 84.14 },
        { voice: "female_1", url: "/audio/pre-gen/gen-b884_female_1.mp3", duration_seconds: 96.63 },
        { voice: "male_1", url: "/audio/pre-gen/gen-b884_male_1.mp3", duration_seconds: 76.17 },
        { voice: "female_3", url: "/audio/pre-gen/gen-b884_female_3.mp3", duration_seconds: 80.38 },
        { voice: "male_2", url: "/audio/pre-gen/gen-b884_male_2.mp3", duration_seconds: 73.17 },
        { voice: "asmr", url: "/audio/pre-gen/gen-b884_asmr.mp3", duration_seconds: 85.93 },
        { voice: "male_3", url: "/audio/pre-gen/gen-b884_male_3.mp3", duration_seconds: 78.48 },
      ],
    },
    {
      id: "gen-6b4b4122c529",
      type: "poem",
      title: "Arjun's Magic Peacock Feather",
      description: "A young boy in ancient India discovers a magical peacock feather that transforms his world through play and wonder.",
      cover: "/covers/peacock-magic.svg",
      text: "Little Arjun found a feather bright,\nBlue and green with golden light.\nFrom Mayura, the peacock king,\nA gift that made his heart sing.\n\nWhen he waved it in the air,\nFlowers bloomed everywhere!\nRainbow colors filled the sky,\nAs magical birds came floating by.\n\nThrough his play, the world grew new,\nFilled with wonder, green and blue.\nArjun learned with joy so deep,\nMagic lives in hearts that leap.\n\nNow he dreams of feathers bright,\nDancing softly through the night.",
      target_age: 4,
      duration: 1,
      like_count: 49,
      save_count: 38,
      view_count: 81,
      categories: ["Fantasy", "Indian Culture", "Transformation", "Play"],
      theme: "fantasy",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_2", url: "/audio/pre-gen/gen-6b4b_female_2.mp3", duration_seconds: 51.88 },
        { voice: "female_1", url: "/audio/pre-gen/gen-6b4b_female_1.mp3", duration_seconds: 58.05 },
        { voice: "female_3", url: "/audio/pre-gen/gen-6b4b_female_3.mp3", duration_seconds: 48.21 },
        { voice: "male_1", url: "/audio/pre-gen/gen-6b4b_male_1.mp3", duration_seconds: 46.31 },
        { voice: "male_2", url: "/audio/pre-gen/gen-6b4b_male_2.mp3", duration_seconds: 45.84 },
        { voice: "male_3", url: "/audio/pre-gen/gen-6b4b_male_3.mp3", duration_seconds: 46.67 },
        { voice: "asmr", url: "/audio/pre-gen/gen-6b4b_asmr.mp3", duration_seconds: 51.66 },
      ],
    },
    {
      id: "gen-2fedd4d6a646",
      type: "poem",
      title: "Nayak and the Forgotten Ice Garden",
      description: "A young Inuit boy discovers a magical ice garden beneath his family's igloo, learning that nature's most precious treasures are often hidden in plain sight.",
      cover: "/covers/ice-garden.svg",
      text: "Deep in the Arctic, where snowflakes dance,\nLived young Nayak in his family's stance,\nAn igloo warm with seal oil light,\nThat glowed like stars throughout the night.\n\nOne morning while his parents slept,\nNayak found a crack that wept,\nWith crystal drops of purest blue,\nThat sparkled with a magic hue.\n\nHe followed down the icy trail,\nThrough passages both narrow and frail,\nUntil he found a garden bright,\nWith frozen flowers, pure delight.\n\nIce tulips bloomed in silver rows,\nAnd crystal trees where arctic wind blows,\nThis secret world beneath their home,\nWhere winter's children freely roam.\n\nHe climbed back up with wonder true,\nTo share this gift of arctic blue,\nFor nature keeps her treasures near,\nIn places that we hold most dear.\n\nNow Nayak dreams of gardens white,\nBeneath his family's loving light,\nWhere magic sleeps in ice and snow,\nAnd peaceful winter breezes blow.",
      target_age: 7,
      duration: 1,
      like_count: 91,
      save_count: 31,
      view_count: 177,
      categories: ["Nature", "Family", "Discovery", "Arctic Adventure"],
      theme: "nature",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_3", url: "/audio/pre-gen/gen-2fed_female_3.mp3", duration_seconds: 85.24 },
        { voice: "female_2", url: "/audio/pre-gen/gen-2fed_female_2.mp3", duration_seconds: 92.22 },
        { voice: "female_1", url: "/audio/pre-gen/gen-2fed_female_1.mp3", duration_seconds: 105.08 },
        { voice: "male_1", url: "/audio/pre-gen/gen-2fed_male_1.mp3", duration_seconds: 79.97 },
        { voice: "male_2", url: "/audio/pre-gen/gen-2fed_male_2.mp3", duration_seconds: 83.84 },
        { voice: "male_3", url: "/audio/pre-gen/gen-2fed_male_3.mp3", duration_seconds: 84.85 },
        { voice: "asmr", url: "/audio/pre-gen/gen-2fed_asmr.mp3", duration_seconds: 91.4 },
      ],
    },
    {
      id: "gen-f23316834cfd",
      type: "poem",
      title: "Mei and the Moonlit Origami Festival",
      description: "A young girl and her forest friends work together to create magical origami creatures for the annual Moonlit Festival, learning that their different talents make the celebration truly special.",
      cover: "/covers/origami-festival.svg",
      text: "In the bamboo forest where the moon shines bright,\nLived brave little Mei with paper folding might.\nShe loved making cranes that could dance and fly,\nBut the festival needed more beneath the sky.\n\nHer friend Hana painted with colors so true,\nWhile Kenji carved dragons from bamboo.\nTaro sang melodies sweet and clear,\nBut Mei felt worried the day drawing near.\n\n\"My origami won't be enough alone,\"\nShe sighed as she sat by the wishing stone.\nBut Hana heard her and had a bright thought,\n\"Together we'll make what cannot be bought!\"\n\nThey painted Mei's cranes in sunset hues,\nKenji carved holders in morning blues.\nTaro's songs made the paper dance,\nGiving each creature a magical chance.\n\nWhen festival night came with silver light,\nTheir origami glowed warm and bright.\nThe village gasped at the wondrous sight,\nFriends working together made everything right.\n\nNow Mei dreams of paper birds that soar,\nWith friends beside her, she could ask for no more.\nIn moonbeams soft, her origami rest,\nKnowing together, they always do their best.",
      target_age: 7,
      duration: 2,
      like_count: 67,
      save_count: 9,
      view_count: 137,
      categories: ["Friendship", "Teamwork", "Creativity", "Fantasy"],
      theme: "friendship",
      musicProfile: "enchanted-garden",
      audio_variants: [
        { voice: "female_2", url: "/audio/pre-gen/gen-f233_female_2.mp3", duration_seconds: 103.58 },
        { voice: "female_3", url: "/audio/pre-gen/gen-f233_female_3.mp3", duration_seconds: 95.94 },
        { voice: "female_1", url: "/audio/pre-gen/gen-f233_female_1.mp3", duration_seconds: 119.33 },
        { voice: "male_1", url: "/audio/pre-gen/gen-f233_male_1.mp3", duration_seconds: 89.87 },
        { voice: "male_2", url: "/audio/pre-gen/gen-f233_male_2.mp3", duration_seconds: 94.03 },
        { voice: "male_3", url: "/audio/pre-gen/gen-f233_male_3.mp3", duration_seconds: 94.85 },
        { voice: "asmr", url: "/audio/pre-gen/gen-f233_asmr.mp3", duration_seconds: 113.18 },
      ],
    },
    {
      id: "gen-df0dbc9d6b74",
      type: "poem",
      title: "Coral's Journey Through the Healing Tides",
      description: "A young ocean spirit discovers how the microscopic world of plankton creates life-giving oxygen, transforming her understanding of the sea's healing powers.",
      cover: "/covers/healing-tides.svg",
      text: "In ancient waters, deep and blue,\nLived Coral, spirit brave and true.\nShe swam through currents, swift and free,\nGuardian of the healing sea.\n\nBut something strange began to show—\nThe waters dimmed, their healing glow\nGrew weak and pale. The fish felt ill,\nThe coral reefs grew cold and still.\n\nThen Coral dove to depths unknown,\nWhere tiny plankton called their home.\nShe watched them dance, so small, so bright,\nCreating oxygen and light.\n\n\"We are the healers!\" they sang sweet,\n\"Through photosynthesis complete!\nWe breathe in sunlight, breathe out air,\nFor every creature, everywhere.\"\n\nNow Coral understood at last—\nThe healing wisdom of the past.\nThe smallest life creates the whole,\nThe ocean's breath, the ocean's soul.\n\nShe guards the plankton, night and day,\nKeeping pollution far away.\nFor in their microscopic dance,\nLies healing's greatest, sweetest chance.",
      target_age: 10,
      duration: 2,
      like_count: 87,
      save_count: 45,
      view_count: 110,
      categories: ["Science", "Ocean", "Transformation", "Healing"],
      theme: "science",
      musicProfile: "cosmic-voyage",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/gen-df0d_female_1.mp3", duration_seconds: 109.21 },
        { voice: "female_3", url: "/audio/pre-gen/gen-df0d_female_3.mp3", duration_seconds: 87.9 },
        { voice: "female_2", url: "/audio/pre-gen/gen-df0d_female_2.mp3", duration_seconds: 97.73 },
        { voice: "male_1", url: "/audio/pre-gen/gen-df0d_male_1.mp3", duration_seconds: 85.78 },
        { voice: "male_3", url: "/audio/pre-gen/gen-df0d_male_3.mp3", duration_seconds: 85.92 },
        { voice: "male_2", url: "/audio/pre-gen/gen-df0d_male_2.mp3", duration_seconds: 90.24 },
        { voice: "asmr", url: "/audio/pre-gen/gen-df0d_asmr.mp3", duration_seconds: 101.16 },
      ],
    },
    {
      id: "gen-e77b10c51e8f",
      type: "poem",
      title: "Diego and the Star Map of the Ancient Temple",
      description: "A young Mayan boy discovers a celestial map in an ancient temple that reveals the connection between earthly friendships and the vast cosmos above.",
      cover: "/covers/star-temple.svg",
      text: "In the jungle green where temples rise,\nLived Diego with his curious eyes,\nHe loved to climb the pyramid stone,\nBut often felt he walked alone.\n\nOne starlit night he found a door,\nHidden deep in temple floor,\nInside, the walls began to glow,\nWith constellations high and low.\n\nThe ancient map showed Venus bright,\nAnd Jupiter's majestic light,\nEach planet danced in painted gold,\nWith stories that the Maya told.\n\nAs Diego traced each starry line,\nHe saw how all the stars align,\nLike friends who come from far and near,\nTo make the night sky bright and clear.\n\nHe learned that just like stars above,\nWe're connected through our love,\nEach friendship is a shining light,\nThat guides us through the darkest night.\n\nNow Diego knows he's not alone,\nThe stars and friends have always shown,\nThat in this cosmic, vast embrace,\nWe each have found our special place.",
      target_age: 10,
      duration: 1,
      like_count: 55,
      save_count: 17,
      view_count: 257,
      categories: ["Space", "Friendship", "Ancient Civilizations", "Self-Discovery"],
      theme: "space",
      musicProfile: "cosmic-voyage",
      audio_variants: [
        { voice: "female_1", url: "/audio/pre-gen/gen-e77b_female_1.mp3", duration_seconds: 101.39 },
        { voice: "female_2", url: "/audio/pre-gen/gen-e77b_female_2.mp3", duration_seconds: 91.83 },
        { voice: "female_3", url: "/audio/pre-gen/gen-e77b_female_3.mp3", duration_seconds: 82.05 },
        { voice: "male_2", url: "/audio/pre-gen/gen-e77b_male_2.mp3", duration_seconds: 79.96 },
        { voice: "male_3", url: "/audio/pre-gen/gen-e77b_male_3.mp3", duration_seconds: 81.55 },
        { voice: "asmr", url: "/audio/pre-gen/gen-e77b_asmr.mp3", duration_seconds: 95.09 },
        { voice: "male_1", url: "/audio/pre-gen/gen-e77b_male_1.mp3", duration_seconds: 76.33 },
      ],
    },
  ],
  hi: [
    {
      id: "seed-neendwala-badal",
      type: "story",
      title: "Neendwala Badal",
      description: "Ek narm-mulaayam badal chaandni raat mein sapne baat-ta phirta hai.",
      cover: COVERS.sleepyCloud,
      text: "Chhat ke upar aasmaan mein, ek chhota sa mulaayam badal tha jiska naam tha Nimbus. Nimbus ka kaam duniya ka sabse khaas kaam tha \u2014 taaron se meethe sapne ikaththa karna aur sote hue bacchon pe chidakna.\n\nAaj raat taare khoob chamak rahe the. Nimbus ne apne narm haathon se ek sapna pakda \u2014 udne waale ghode ka, ek aur candy ke baag ka, aur ek pyaare dragon ka jo garam jhappi dena chahta tha.\n\nJab Nimbus tumhare ghar ke upar se guzra, usne apna phulphula badan hilaya, aur sapne chhoti chhoti barf ki phuhar ki tarah neeche aaye. Wo tumhare takkiye pe aaram se baith gaye, tumhara aankhein band karne ka intezaar kar rahe the.\n\n\"Meethe sapne dekho, chhote,\" Nimbus ne dheere se kaha, aur chaandni ki lakeer chhodta hua aage nikal gaya.",
      target_age: 4,
      duration: 3,
      like_count: 57,
      save_count: 88,
      view_count: 160,
      categories: ["Kalpana", "Lori", "Jaadui"],
      theme: "dreamy",
      musicProfile: "dreamy-clouds",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-neend_female_1_hi.mp3", duration_seconds: 78.78 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-neend_female_2_hi.mp3", duration_seconds: 82.97 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-neend_female_3_hi.mp3", duration_seconds: 89.38 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-neend_asmr_hi.mp3", duration_seconds: 80.09 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-neend_male_1_hi.mp3", duration_seconds: 79.9 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-neend_male_2_hi.mp3", duration_seconds: 77.7 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-neend_male_3_hi.mp3", duration_seconds: 81.91 },
      ],
    },
    {
      id: "seed-bahadur-jugnu",
      type: "story",
      title: "Bahadur Chhota Jugnu",
      description: "Ek chhota sa jugnu bhule hue jaanwaron ko ghar ka raasta dikhata hai.",
      cover: COVERS.braveFirefly,
      text: "Gungunate Jungle ke beech mein ek chhota sa jugnu rehta tha jiska naam tha Flicker. Baaki jugnuon ki tarah uski roshni chamakdaar nahi thi \u2014 bilkul ek chhoti si mombatti jaisi.\n\nLekin usi raat, ek chhota khargosh Clover jungle ke sabse andhere hisse mein kho gaya. \"Meri roshni ke peeche aao!\" Flicker ne kaha. Roshni chhoti thi, lekin Clover ko har kadam dikhane ke liye kaafi thi.\n\nSaath mein chale, Flicker raasta dikhata raha, jab tak Clover apne ghar nahi pahunch gaya jahan Mamma Rabbit intezaar kar rahi thi.\n\n\"Shukriya, chhoti roshni,\" Clover ne unghaate hue kaha. \"Tum pure jungle ke sabse bahadur jugnu ho.\"\n\nAur us raat ke baad, Flicker ne kabhi khud ko chhota nahi samjha. Kyunki chhoti si roshni bhi kisi ko ghar pahuncha sakti hai.",
      target_age: 5,
      duration: 4,
      like_count: 92,
      save_count: 16,
      view_count: 191,
      categories: ["Janwar", "Sahas", "Dosti"],
      theme: "adventure",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-bahad_female_1_hi.mp3", duration_seconds: 81.3 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-bahad_female_2_hi.mp3", duration_seconds: 84.43 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-bahad_female_3_hi.mp3", duration_seconds: 91.84 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-bahad_asmr_hi.mp3", duration_seconds: 79.72 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-bahad_male_1_hi.mp3", duration_seconds: 96.54 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-bahad_male_2_hi.mp3", duration_seconds: 98.5 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-bahad_male_3_hi.mp3", duration_seconds: 87.59 },
      ],
    },
    {
      id: "seed-chaand-ki-lori",
      type: "story",
      title: "Chaand ki Lori",
      description: "Chaand apni meethi lori se sabhi jaanwaron ko sulata hai.",
      cover: COVERS.moonLullaby,
      text: "Jab suraj pahaadiyon ke peeche chala gaya, Chaand dheere-dheere uthha aur Willow Meadow pe chandi ki roshni bikher di.\n\n\"Chup ho ja, chhoti lomdi,\" Chaand ne gaaya, aur lomdi apni khoh mein simat gayi.\n\n\"So ja, chhote ullu,\" Chaand ne gungunaya, aur ullu ne apna sar apne pankh ke neeche chhupa liya.\n\nPhir Chaand ne tumhari taraf dekha aur sabse meetha sur gaaya: \"Shubh raatri, mere chhote sapne dekhne waale. Subah tak taare tumhara khayal rakhenge.\"\n\nAur bas phir, poori duniya sukoon se so gayi.",
      target_age: 3,
      duration: 3,
      like_count: 99,
      save_count: 10,
      view_count: 427,
      categories: ["Lori", "Janwar", "Prakriti"],
      theme: "fairy_tale",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-chaan_female_1_hi.mp3", duration_seconds: 54.44 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-chaan_female_2_hi.mp3", duration_seconds: 55.57 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-chaan_female_3_hi.mp3", duration_seconds: 52.87 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-chaan_asmr_hi.mp3", duration_seconds: 52.27 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-chaan_male_1_hi.mp3", duration_seconds: 58.12 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-chaan_male_2_hi.mp3", duration_seconds: 55.46 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-chaan_male_3_hi.mp3", duration_seconds: 52.56 },
      ],
    },
    {
      id: "seed-captain-sitaara",
      type: "story",
      title: "Captain Sitaara aur Dhumketu ki Race",
      description: "Ek space explorer dhumketu se race lagati hai birthday wish dene ke liye.",
      cover: COVERS.captainStardust,
      text: "Captain Sitaara ne apna chamakdar helmet theek kiya aur apne starship Silver Dreamer ka control pakda. Aaj ki mission sabse zaroori thi \u2014 Planet Cakealot pe birthday wish pahunchana, aadhi raat se pehle!\n\nSilver Dreamer Saturn ke chhalon ke beech se nikli, asteroid field ko dodge kiya, aur ek neele dhumketu Flash ke saath race lagayi.\n\nWo bilkul sahi waqt pe pahunchi! Captain Sitaara ne wish deliver ki \u2014 ek chamakta sona sitaara.\n\n\"Mission poora hua,\" usne muskuraate hue kaha. \"Ab ghar chalein. Space explorers ko bhi neend aati hai.\"\n\nAur jab Silver Dreamer shaant aasmaan se ghar laut rahi thi, taaron ne bhi apni roshni dheemi ki aur shubh raatri kahi.",
      target_age: 7,
      duration: 4,
      like_count: 109,
      save_count: 84,
      view_count: 394,
      categories: ["Antariksh", "Sahas"],
      theme: "space",
      musicProfile: "cosmic-voyage",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-capta_female_1_hi.mp3", duration_seconds: 74.63 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-capta_female_2_hi.mp3", duration_seconds: 73.6 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-capta_female_3_hi.mp3", duration_seconds: 75.61 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-capta_asmr_hi.mp3", duration_seconds: 69.09 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-capta_male_1_hi.mp3", duration_seconds: 75.74 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-capta_male_2_hi.mp3", duration_seconds: 76.73 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-capta_male_3_hi.mp3", duration_seconds: 67.25 },
      ],
    },
    {
      id: "seed-gungunata-baag",
      type: "story",
      title: "Gungunata Baag",
      description: "Ek jaadui baag jahan phool kahaniyan sunate hain.",
      cover: COVERS.gardenWhispers,
      text: "Daadi ke ghar ke peeche, Maya ko ek aisa baag mila jo sone ki roshni se chamak raha tha. Yahan ke phool jaadui the \u2014 gulaab jo lantern ki tarah chamakte the, lily jo dhun gaati thi.\n\nHar phool ke paas ek alag kahani thi. Daisy chuhon ki bahaduri ki kahani sunati thi. Tulip meherbaani ki puraani kathayein batati thi. Lavender chaandni raaton ki kavitayein sunata tha.\n\nHar kahani aise khatam hoti thi: \"Ab aankhein band karo, pyaare. Kal ek aur kahani tumhara intezaar kar rahi hogi.\"",
      target_age: 8,
      duration: 5,
      like_count: 181,
      save_count: 36,
      view_count: 129,
      categories: ["Jaadui", "Kalpana", "Prakriti"],
      theme: "fantasy",
      musicProfile: "enchanted-garden",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-gungu_female_1_hi.mp3", duration_seconds: 62.02 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-gungu_female_2_hi.mp3", duration_seconds: 66.75 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-gungu_female_3_hi.mp3", duration_seconds: 75.93 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-gungu_asmr_hi.mp3", duration_seconds: 56.05 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-gungu_male_1_hi.mp3", duration_seconds: 66.11 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-gungu_male_2_hi.mp3", duration_seconds: 77.39 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-gungu_male_3_hi.mp3", duration_seconds: 63.38 },
      ],
    },
    {
      id: "seed-chamakta-sapna",
      type: "poem",
      title: "Chamakta Sapna",
      description: "Taaron ki nigrani mein sone ki meethi kavita.",
      cover: COVERS.twinkleDream,
      text: "Taare jhilmil karte hain aasmaan mein,\nTumhare sapne basate hain unki chaan mein.\nChaanda muskuraye gol chamakdaar,\nChaandi mein lapet le saara sansaar.\n\nAankhein moondo ab, mere pyaare taare,\nRaat aayi hai, jag uthe sitaare.\nKal subah suraj naya aayega,\nPar ab sapnon ka jahan le jaayega.",
      target_age: 3,
      duration: 2,
      like_count: 27,
      save_count: 82,
      view_count: 386,
      categories: ["Lori", "Jaadui"],
      theme: "dreamy",
      musicProfile: "starlight-lullaby",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-chama_female_1_hi.mp3", duration_seconds: 26.78 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-chama_female_2_hi.mp3", duration_seconds: 28.61 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-chama_female_3_hi.mp3", duration_seconds: 30.07 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-chama_asmr_hi.mp3", duration_seconds: 30.29 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-chama_male_1_hi.mp3", duration_seconds: 30.93 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-chama_male_2_hi.mp3", duration_seconds: 30.22 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-chama_male_3_hi.mp3", duration_seconds: 27.48 },
      ],
    },
    {
      id: "seed-ullu-ki-shubhraatri",
      type: "poem",
      title: "Ullu ki Shubh Raatri",
      description: "Ek samajhdaar ullu jungle ke har praani ko shubh raatri kehta hai.",
      cover: COVERS.owlGoodnight,
      text: "Uhoo-uhoo, ullu bole budhe pedh se,\nShubh raatri machli ko neeli nadiya ke desh se.\nShubh raatri khargosh ko garm bistar mein,\nShubh raatri ladybug ko phoolon ke ghar mein.\n\nUhoo-uhoo, lomdi so ja apni khoh mein,\nBatakh aur murgi bhi sapnon ki choh mein.\nShubh raatri gilahri ko meethi neend aaye,\nUhoo-uhoo, mere bachche \u2014 ab chain se so jaaye.",
      target_age: 2,
      duration: 2,
      like_count: 133,
      save_count: 60,
      view_count: 200,
      categories: ["Janwar", "Lori"],
      theme: "animals",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-ullu-_female_1_hi.mp3", duration_seconds: 30.41 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-ullu-_female_2_hi.mp3", duration_seconds: 28.12 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-ullu-_female_3_hi.mp3", duration_seconds: 33.86 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-ullu-_asmr_hi.mp3", duration_seconds: 33.84 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-ullu-_male_1_hi.mp3", duration_seconds: 28.49 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-ullu-_male_2_hi.mp3", duration_seconds: 33.13 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-ullu-_male_3_hi.mp3", duration_seconds: 29.96 },
      ],
    },
    {
      id: "seed-sapnon-ki-naav",
      type: "song",
      title: "Sapnon ki Naav",
      description: "Chaandni raat mein sapnon ke desh ki taraf le jaane wala gaana.",
      cover: COVERS.sailingDreamland,
      text: "[Verse 1]\nChandi ki naav pe hum sawaar chalein,\nChaandni samundar ke paar chalein.\nTaare gaate hain lori meethi pyaari,\nLe chalein sapnon ki phulajhaari.\n\n[Chorus]\nSapnon ka desh, sapnon ka desh, aao chalein,\nBaigani aasmaan mein udte chalein.\nSapnon ka desh, sapnon ka desh, raat suhaani,\nChintaon ko bhool jaao, suno yeh kahaani.",
      target_age: 4,
      duration: 2,
      like_count: 20,
      save_count: 25,
      view_count: 285,
      categories: ["Lori", "Jaadui"],
      theme: "dreamy",
      musicProfile: "ocean-drift",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/hi-sapno_female_1_hi.mp3", duration_seconds: 26.28 },
        { voice: "female_2_hi", url: "/audio/pre-gen/hi-sapno_female_2_hi.mp3", duration_seconds: 28.43 },
        { voice: "female_3_hi", url: "/audio/pre-gen/hi-sapno_female_3_hi.mp3", duration_seconds: 27.57 },
        { voice: "asmr_hi", url: "/audio/pre-gen/hi-sapno_asmr_hi.mp3", duration_seconds: 30.99 },
        { voice: "male_1_hi", url: "/audio/pre-gen/hi-sapno_male_1_hi.mp3", duration_seconds: 26.48 },
        { voice: "male_2_hi", url: "/audio/pre-gen/hi-sapno_male_2_hi.mp3", duration_seconds: 20.14 },
        { voice: "male_3_hi", url: "/audio/pre-gen/hi-sapno_male_3_hi.mp3", duration_seconds: 25.48 },
      ],
    },
    {
      id: "gen-593c43ad1c11",
      type: "story",
      title: "Nanha Sitara Aur Uski Neend Ki Lori",
      description: "Ek chhota sitara jungle mein sabko neend dilata hai apni komal roshni se.",
      cover: "/covers/nanha-sitara.svg",
      text: "नन्हा सितारा चमका।  शश शश, नींद आ रही।  जंगल सोता, सितारा जगता।  कोमल रोशनी, कोमल रोशनी।  पत्ते हिलते, हवा चलती।  शश शश, नींद आ गई।  सितारा मुस्काया, सब सो गए।",
      target_age: 0,
      duration: 1,
      like_count: 32,
      save_count: 50,
      view_count: 60,
      categories: ["Nature", "Fantasy", "Sleep"],
      theme: "nature",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-593c_female_1_hi.mp3", duration_seconds: 30.33 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-593c_female_2_hi.mp3", duration_seconds: 33.63 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-593c_female_3_hi.mp3", duration_seconds: 36.2 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-593c_male_1_hi.mp3", duration_seconds: 32.72 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-593c_male_2_hi.mp3", duration_seconds: 48.34 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-593c_male_3_hi.mp3", duration_seconds: 58.01 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-593c_asmr_hi.mp3", duration_seconds: 28.66 },
      ],
    },
    {
      id: "gen-b2e7514e8b8f",
      type: "story",
      title: "Nano Khargosh Aur Samudri Dost",
      description: "Ek chhota khargosh aur uska naya samudri dost saath mein sote hain.",
      cover: "/covers/samudri-dost.svg",
      text: "नैनो खरगोश। नीला पानी।  श्श श्श श्श। मछली दोस्त।  हां हां हां। साथ में खेल।  चुप चुप चुप। गर्म रेत।  सो जाओ सो जाओ। मीठे सपने।",
      target_age: 0,
      duration: 1,
      like_count: 91,
      save_count: 39,
      view_count: 280,
      categories: ["Ocean Adventure", "Friendship", "Baby Sleep"],
      theme: "ocean",
      musicProfile: "ocean-drift",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-b2e7_female_1_hi.mp3", duration_seconds: 26.05 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-b2e7_female_3_hi.mp3", duration_seconds: 22.14 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-b2e7_female_2_hi.mp3", duration_seconds: 32.3 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-b2e7_male_1_hi.mp3", duration_seconds: 17.11 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-b2e7_male_2_hi.mp3", duration_seconds: 28.9 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-b2e7_male_3_hi.mp3", duration_seconds: 25.68 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-b2e7_asmr_hi.mp3", duration_seconds: 22.8 },
      ],
    },
    {
      id: "gen-376993c8e295",
      type: "poem",
      title: "Asha Ki Barf Mein Soft Bistar Ki Talash",
      description: "Ek brave ladki Asha Arctic mein apne polar bear dost ke saath sabse soft bistar dhundne ka journey karti hai.",
      cover: "/covers/barf-bistar.svg",
      text: "आशा एक ब्रेव लड़की थी, बर्फ में रहती थी   पोलर बेयर दोस्त के साथ, सॉफ्ट बिस्तर ढूंढती थी   बर्फ पर चलते गए, फ्लफी स्नो में   मिल गया कोजी जगह, वार्म और क्लीन   आशा और बेयर सो गए, सॉफ्ट बर्फ के बिस्तर में   सपनों में उड़ती रही, आर्कटिक के सितारों में",
      target_age: 2,
      duration: 1,
      like_count: 92,
      save_count: 39,
      view_count: 159,
      categories: ["Nature", "Friendship", "Adventure"],
      theme: "nature",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-3769_female_1_hi.mp3", duration_seconds: 38.05 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-3769_female_2_hi.mp3", duration_seconds: 44.73 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-3769_female_3_hi.mp3", duration_seconds: 37.64 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-3769_male_1_hi.mp3", duration_seconds: 38.46 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-3769_male_3_hi.mp3", duration_seconds: 44.71 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-3769_male_2_hi.mp3", duration_seconds: 35.9 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-3769_asmr_hi.mp3", duration_seconds: 32.3 },
      ],
    },
    {
      id: "gen-aad0a6e0c0c0",
      type: "poem",
      title: "Kira Ka Samudri Ghar Ki Khoj",
      description: "Ek brave chhoti ladki Kira apne island ghar mein family ke saath naye kamre discover karti hai aur cozy sleeping jagah paati hai.",
      cover: "/covers/samudri-ghar.svg",
      text: "किरा छोटी brave गर्ल थी, आइसलैंड पे रहती थी\nफैमिली के साथ warm घर में, खुशी से हंस रही थी\n\nमामा पापा के साथ, नया रूम ढूंढा उसने\nबैंबू वॉल्स और soft मैट्स, देखा ओशन व्यू से\n\nग्रैंडमा ने कहा 'देखो बेटा', शेल्स और पर्ल्स यहां\nफैमिली का पुराना ट्रेजर, मिल गया है घर में\n\nवेव्स की आवाज़ सुन कर, किरा टायर्ड हो गई\nसॉफ्ट मैट पे lie down करके, फैमिली के पास सो गई\n\nओशन ब्रीज़ से लुल्लाबी, स्टार्स शाइनिंग ब्राइट\nफैमिली का लव और वार्मथ, गुड नाइट स्वीट नाइट",
      target_age: 2,
      duration: 1,
      like_count: 30,
      save_count: 36,
      view_count: 75,
      categories: ["Family", "Adventure", "Ocean", "Home", "Discovery"],
      theme: "family",
      musicProfile: "dreamy-clouds",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-aad0_female_1_hi.mp3", duration_seconds: 61.79 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-aad0_female_2_hi.mp3", duration_seconds: 62.84 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-aad0_female_3_hi.mp3", duration_seconds: 55.13 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-aad0_male_1_hi.mp3", duration_seconds: 60.54 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-aad0_male_2_hi.mp3", duration_seconds: 60.59 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-aad0_male_3_hi.mp3", duration_seconds: 51.6 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-aad0_asmr_hi.mp3", duration_seconds: 64.33 },
      ],
    },
    {
      id: "gen-ddc437037568",
      type: "story",
      title: "Dosti ki Kahani",
      description: "Ek fantasy realm mein, Nova aur uske doston ne milkar ek mushkil ko hal kiya aur dosti ki sachchai samjhe. Ye kahani dosti, teamwork, aur samajh ki mahatta ko darshati hai.",
      cover: "/covers/dosti-kahani.svg",
      text: "एक छोटा सा शहर था, जिसका नाम एथोरिया था, जहां पर लोगों के दिल में प्यार और दोस्ती भर गयी थी.  यहां पर नोवा, एक १५ साल का नॉन-बाइनरी टीन, अपने दोस्तों के साथ मिलकर एक अनोखा सफर पर निकल पड़ता है.  उनका पहला मिशन था, एक पुरानी मंदिर की तलाश, जहां पर एक प्राचीन खजाना छुपा हुआ था.  नोवा के साथ थे उसके दोस्त, जारा, अर्जुन, और लीला, जो अपने-अपने खास हुनर के साथ आए थे.  साथ मिलकर, वे सभी ने मुश्किल रास्तों पर चलकर मंदिर तक पहुंचने की कोशिश की.  लेकिन, जब वे अंदर घुसते हैं, तो उन्हें एक अनोखी चुनौती का सामना करना पड़ता है.  उन्हें एक प्राचीन पज़ल को सुलझाना होता है, जो केवल तब ही सुलझेगा जब वे अपने हुनर को एक साथ मिलाकर इस्तेमाल करेंगे.  नोवा और उसके दोस्त सभी ने मिलकर काम किया, और पज़ल को सुलझाया.  अब, वे सभी घर वापस आने के लिए तैयार हैं, और एक नए दिन की शुरुआत के लिए उत्सुक हैं.",
      target_age: 13,
      duration: 1,
      like_count: 81,
      save_count: 23,
      view_count: 154,
      categories: ["Fantasy", "Dosti", "Teamwork"],
      theme: "friendship",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-ddc4_female_1_hi.mp3", duration_seconds: 83.19 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-ddc4_female_2_hi.mp3", duration_seconds: 91.72 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-ddc4_female_3_hi.mp3", duration_seconds: 85.53 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-ddc4_male_1_hi.mp3", duration_seconds: 84.76 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-ddc4_male_3_hi.mp3", duration_seconds: 77.0 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-ddc4_male_2_hi.mp3", duration_seconds: 85.45 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-ddc4_asmr_hi.mp3", duration_seconds: 82.9 },
      ],
    },
    {
      id: "gen-2b9fdf8a1222",
      type: "poem",
      title: "Riya ki Prakriti Yatra",
      description: "Riya, a brave child, embarks on a quest journey to appreciate nature and understand environmental awareness in the Americas, specifically in the contemporary world of North America.",
      cover: "/covers/prakriti-yatra.svg",
      text: "रिया एक छोटे से जंगल में गयी,  जहां पेड़ों के नीचे एक सुंदर ताल था.  उसने देखा कि ताल के किनारे पर कई जानवर थे, जो पानी पीने आए थे.\nरिया ने सोचा कि प्रकृति कितनी सुंदर है,  और हमें उसकी रक्षा करनी चाहिए.  उसने अपने आप से वादा किया कि वो हमेशा प्रकृति की रक्षा करेगी.\nअब रिया  सोने जा रही है, और वो चाहती है कि तुम भी प्रकृति की रक्षा करो.",
      target_age: 13,
      duration: 1,
      like_count: 77,
      save_count: 33,
      view_count: 183,
      categories: ["Prakriti", "Paryavaran"],
      theme: "nature",
      musicProfile: "forest-night",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-2b9f_female_1_hi.mp3", duration_seconds: 45.1 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-2b9f_female_2_hi.mp3", duration_seconds: 43.06 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-2b9f_female_3_hi.mp3", duration_seconds: 44.31 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-2b9f_male_2_hi.mp3", duration_seconds: 50.72 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-2b9f_male_1_hi.mp3", duration_seconds: 47.29 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-2b9f_asmr_hi.mp3", duration_seconds: 45.83 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-2b9f_male_3_hi.mp3", duration_seconds: 43.19 },
      ],
    },
    {
      id: "gen-60370cf66525",
      type: "poem",
      title: "Naina Ki Baraf Waley School Mein Seal Dost Ki Khoj",
      description: "Brave Naina discovers a magical Arctic school where she learns from friendly seals and makes wonderful new friends.",
      cover: "/covers/seal-school.svg",
      text: "बर्फ के घर में एक दिन, नैना पहुंची स्कूल\nजहाँ सील मछलियाँ पढ़ती, बर्फ का यह रूल\n\nसुनो सुनो कहती सील, हम सिखायेंगे तुम्हें\nबर्फ पर कैसे खेलना, पानी में कैसे रहना\n\nनैना ने सीखा डाइविंग, सील के साथ खेला\nआर्कटिक के जादुई राज़, सबने मिल कर देखा\n\nदोस्त बन गए सब मिलकर, बर्फ में हंसकर\nनैना की खुशी देखो, सीख गई नई कला\n\nअब नैना सपनों में जाये, सील दोस्त के साथ\nबर्फ वाले स्कूल की यादें, लेके जाये साथ",
      target_age: 4,
      duration: 1,
      like_count: 81,
      save_count: 12,
      view_count: 75,
      categories: ["Animals", "Friendship", "Learning", "Adventure"],
      theme: "animals",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-6037_female_1_hi.mp3", duration_seconds: 54.37 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-6037_female_2_hi.mp3", duration_seconds: 58.48 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-6037_female_3_hi.mp3", duration_seconds: 54.72 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-6037_male_1_hi.mp3", duration_seconds: 54.95 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-6037_male_2_hi.mp3", duration_seconds: 49.56 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-6037_male_3_hi.mp3", duration_seconds: 61.02 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-6037_asmr_hi.mp3", duration_seconds: 53.87 },
      ],
    },
    {
      id: "gen-032fdef6f753",
      type: "poem",
      title: "Vaanar Mitra Ka Jaadui Khel Samrajya",
      description: "Ek chhote vaanar ka ek magical playground mein transformation ka safar, jahaan woh seekhta hai ki khel mein discovery ki shakti hai.",
      cover: "/covers/monkey-kingdom.svg",
      text: "एक छोटा वानर था, हन्नू नाम का प्यारा\nएक जादुई वन में खेलता, सपनों का नज़ारा\n\nझूलों पर नाचता, रंग बदल जाते थे\nहर खेल में कुछ नया, सपने सच हो जाते थे\n\nपत्थर छूते तो तितली, पानी में तारे\nहन्नू का दिल खुशी से, भर गया सितारे\n\nखेल खेल में सीखा, दुनिया की यह बात\nहर चीज़ में छुपा है, कुछ जादुई रात",
      target_age: 4,
      duration: 1,
      like_count: 99,
      save_count: 7,
      view_count: 159,
      categories: ["Fantasy", "Adventure", "Transformation", "Play"],
      theme: "fantasy",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-032f_female_1_hi.mp3", duration_seconds: 42.57 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-032f_female_2_hi.mp3", duration_seconds: 44.37 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-032f_female_3_hi.mp3", duration_seconds: 44.59 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-032f_male_1_hi.mp3", duration_seconds: 45.35 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-032f_male_3_hi.mp3", duration_seconds: 43.81 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-032f_male_2_hi.mp3", duration_seconds: 38.97 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-032f_asmr_hi.mp3", duration_seconds: 45.22 },
      ],
    },
    {
      id: "gen-febbf324eecb",
      type: "poem",
      title: "Kiran Aur Samudar Ke Upar Ke Floating Islands Ki Dosti",
      description: "Bhavishya mein samudar ke upar tairte hue magical islands par rehne wala ek brave ladka Kiran apne robot dost ke saath naye friends banata hai.",
      cover: "/covers/floating-islands.svg",
      text: "समुद्र के ऊपर, आसमान में high,\nतैरते हुए islands, crystals की light।\nकिरण नाम का लड़का, brave और sweet,\nRobot दोस्त Sparky के साथ, adventures complete।\n\nFloating gardens में flowers glow करते,\nHolographic butterflies dance करते।\nकिरण lonely feel करता था sometimes,\nनये friends की search में, climbing heights।\n\nएक दिन मिले Luna, mermaid so kind,\nऔर Zephyr wind-sprite, pure of mind।\nTogether they explored crystal caves deep,\nSharing stories, promises to keep।\n\nFloating bridges of light उन्हें connect करते,\nDifferent islands, hearts को reflect करते।\nकिरण ने सीखा, friendship का magic true,\nDistance doesn't matter, when hearts are blue।\n\nStarfish lanterns light up the night,\nFriends gather 'round, everything's right।\nसमुद्र की waves, gentle lullaby sing,\nदोस्ती की warmth, peaceful dreams bring।\n\nNow किरण sleeps on his island home,\nNo more alone, no need to roam।\nसपनों में friends, always near,\nFuture's bright, nothing to fear।",
      target_age: 7,
      duration: 2,
      like_count: 62,
      save_count: 47,
      view_count: 104,
      categories: ["Fantasy", "Friendship", "Adventure", "Future", "Magic"],
      theme: "fantasy",
      musicProfile: "moonlit-meadow",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-febb_female_1_hi.mp3", duration_seconds: 87.89 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-febb_female_2_hi.mp3", duration_seconds: 102.97 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-febb_male_1_hi.mp3", duration_seconds: 101.04 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-febb_female_3_hi.mp3", duration_seconds: 108.68 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-febb_male_3_hi.mp3", duration_seconds: 91.28 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-febb_male_2_hi.mp3", duration_seconds: 88.97 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-febb_asmr_hi.mp3", duration_seconds: 93.17 },
      ],
    },
    {
      id: "gen-230502b905ba",
      type: "poem",
      title: "Priya Aur Vidya Devi Ki Jaadui Shiksha Yatra",
      description: "Ek brave bachhi Priya ek mythological gurukul mein jaadui gyan seekhti hai aur apne andar ki shakti discover karti hai.",
      cover: "/covers/vidya-devi.svg",
      text: "प्रिया एक छोटी सी बच्ची थी, brave और smart\nविद्या देवी के गुरुकुल में, सीखने गई art\n\nपहाड़ों के बीच में था ये जादुई school\nयहाँ हर बच्चा बनता था ज्ञान का jewel\n\nदेवी ने कहा, \"बेटा, तुम्हारे अंदर है light\nसबको सिखाओ, करो सब कुछ right\"\n\nप्रिया ने सिखाई दूसरों को math और song\nसबके साथ मिलकर, बनी friendship strong\n\nअब वो teacher बन गई, kind और wise\nसपनों में भी सिखाती, under starry skies",
      target_age: 7,
      duration: 1,
      like_count: 43,
      save_count: 12,
      view_count: 222,
      categories: ["Adventure", "Mythology", "School", "Transformation"],
      theme: "adventure",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-2305_female_1_hi.mp3", duration_seconds: 50.02 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-2305_female_2_hi.mp3", duration_seconds: 54.24 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-2305_female_3_hi.mp3", duration_seconds: 53.56 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-2305_male_1_hi.mp3", duration_seconds: 57.09 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-2305_male_2_hi.mp3", duration_seconds: 52.83 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-2305_male_3_hi.mp3", duration_seconds: 51.8 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-2305_asmr_hi.mp3", duration_seconds: 54.27 },
      ],
    },
    {
      id: "gen-bb82f62942d0",
      type: "poem",
      title: "Samudra ki Chhupi Duniya",
      description: "Ek bahadur bachche ki kahani jo samudra ki gahrayi mein jaati hai aur wahaan ke jaadui jeevan ko dekhti hai",
      cover: "/covers/samudra-duniya.svg",
      text: "एक बहादुर बच्चा था, जिसका नाम आरव था,  जो समुद्र की किनारे रहता था.\nवहां पर उसने पानी के नीचे की दुनिया को देखा,  जहां मछलियां और अन्य जीव रहते थे.\nउसने देखा कि कैसे पानी की गति और धीरे-धीरे बदलती गति  समुद्र की लहरों को बनाती है,  और कैसे यह सब कुछ एक दूसरे से जुड़ा हुआ है.",
      target_age: 10,
      duration: 1,
      like_count: 69,
      save_count: 17,
      view_count: 81,
      categories: ["Science", "Mythology"],
      theme: "science",
      musicProfile: "enchanted-garden",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-bb82_female_1_hi.mp3", duration_seconds: 31.57 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-bb82_female_2_hi.mp3", duration_seconds: 41.31 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-bb82_female_3_hi.mp3", duration_seconds: 42.71 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-bb82_male_1_hi.mp3", duration_seconds: 33.78 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-bb82_male_2_hi.mp3", duration_seconds: 39.65 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-bb82_male_3_hi.mp3", duration_seconds: 40.36 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-bb82_asmr_hi.mp3", duration_seconds: 40.47 },
      ],
    },
    {
      id: "gen-0027e1835f09",
      type: "story",
      title: "Advait aur Uske Doston ki Bhavishya Yatra",
      description: "Ek 10 varsh ka ladka advait apne doston ke saath ek bhavishya yatra par jata hai, jaha unhe nayi cheezein seekhne aur apne doston ke saath masti karne ka mauka milta hai. Is yatra mein ve apne aaspas ke sansar ko samajhne aur apne lakshyon ko praapt karne ke liye kai chunautiyon ka saamna karte hain.",
      cover: "/covers/bhavishya-yatra.svg",
      text: "अद्वैत एक छोटे से लद्दाख मठ में रहता था, जहाँ उसने अपने दोस्तों के साथ मिलकर काई नई चीजें सीखी.  एक दिन, उनके शिक्षक ने उन्हें एक नई यात्रा के लिए तैयार किया, जहाँ वे भविष्य के बारे में सीखने जाने वाले थे.  अद्वैत और उसके दोस्तों ने अपने बैग पैक किए और यात्रा के लिए तैयार हो गए.  वे एक भविष्य के शहर में पहुँचे, जहाँ उन्हें काई ऐसी चीजें मिली जो वे पहले कभी नहीं देखे थे.  उन्होंने एक रोबोट्स के साथ मिलकर एक मेज़ में से गुजरना सीखा, जहाँ उन्हें अपने लक्ष्यों को प्राप्त करने के लिए काई चुनौतियों का सामना करना पड़ा.  फिर वे एक भविष्य के पार्क में गए, जहाँ उन्हें काई ऐसी चीजें मिली जो उस समय नहीं थी.  अद्वैत और उसके दोस्तों ने एक साथ खेलते हुए और हँसते हुए काई पल बिताए.  लेकिन फिर, उन्हें एक समस्या का सामना करना पड़ा, जहाँ उन्हें अपने दोस्तों के साथ मिलकर एक समाधान निकालना था.  और तबhi, अद्वैत ने अपने दोस्तों के साथ मिलकर एक ऐसा समाधान निकाला जो उन्हें सबको खुशी दिला सकता था.  अब अद्वैत और उसके दोस्तों को अपनी यात्रा के बारे में सोचकर नींद आ रही थी, और वे अपने अगले दिन की यात्रा के लिए तैयार हो रहे थे.",
      target_age: 10,
      duration: 2,
      like_count: 29,
      save_count: 27,
      view_count: 189,
      categories: ["भविष्य", "दोस्ती", "सीखना"],
      theme: "adventure",
      musicProfile: "autumn-forest",
      audio_variants: [
        { voice: "female_1_hi", url: "/audio/pre-gen/gen-0027_female_1_hi.mp3", duration_seconds: 103.15 },
        { voice: "female_3_hi", url: "/audio/pre-gen/gen-0027_female_3_hi.mp3", duration_seconds: 103.0 },
        { voice: "male_1_hi", url: "/audio/pre-gen/gen-0027_male_1_hi.mp3", duration_seconds: 101.48 },
        { voice: "female_2_hi", url: "/audio/pre-gen/gen-0027_female_2_hi.mp3", duration_seconds: 108.8 },
        { voice: "male_2_hi", url: "/audio/pre-gen/gen-0027_male_2_hi.mp3", duration_seconds: 105.89 },
        { voice: "asmr_hi", url: "/audio/pre-gen/gen-0027_asmr_hi.mp3", duration_seconds: 104.36 },
        { voice: "male_3_hi", url: "/audio/pre-gen/gen-0027_male_3_hi.mp3", duration_seconds: 96.69 },
      ],
    },
  ],
};

/** Helper to get stories for current language */
export function getStories(lang = 'en') {
  return SEED_STORIES[lang] || SEED_STORIES.en;
}
