'use client';

import { useEffect, useState, useRef } from 'react';
import styles from './lullabies.module.css';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

export default function LullabiesPage() {
  const [lullabies, setLullabies] = useState([]);
  const [loading, setLoading] = useState(true);
  const [playing, setPlaying] = useState(null); // id of currently playing
  const audioRef = useRef(null);

  useEffect(() => {
    fetch(`${API_URL}/api/v1/lullabies`)
      .then(r => r.json())
      .then(data => {
        setLullabies(data.data?.items || []);
        setLoading(false);
      })
      .catch(err => {
        console.error('Failed to load lullabies:', err);
        setLoading(false);
      });
  }, []);

  const handlePlay = (lullaby) => {
    if (playing === lullaby.id) {
      // Pause
      audioRef.current?.pause();
      setPlaying(null);
      return;
    }

    // Play new
    if (audioRef.current) {
      audioRef.current.pause();
    }
    const audio = new Audio(`/audio/lullabies/${lullaby.audio_file}`);
    audio.onended = () => setPlaying(null);
    audio.play().catch(console.error);
    audioRef.current = audio;
    setPlaying(lullaby.id);
  };

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current = null;
      }
    };
  }, []);

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.header}>
          <h1 className={styles.title}>Lullabies</h1>
          <p className={styles.subtitle}>Loading...</p>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1 className={styles.title}>Lullabies</h1>
        <p className={styles.subtitle}>
          Test lullabies — {lullabies.length} songs generated by YuE
        </p>
      </div>

      <div className={styles.grid}>
        {lullabies.map((lullaby) => (
          <div key={lullaby.id} className={styles.card}>
            <div className={styles.coverWrap}>
              <object
                data={`/covers/lullabies/${lullaby.cover_file}`}
                type="image/svg+xml"
                className={styles.cover}
                aria-label={lullaby.title}
              >
                <div className={styles.coverFallback}>
                  <span>{lullaby.title?.[0] || '~'}</span>
                </div>
              </object>
            </div>

            <div className={styles.info}>
              <h3 className={styles.cardTitle}>{lullaby.title}</h3>
              <p className={styles.cardSubtitle}>{lullaby.card_subtitle}</p>
              <div className={styles.meta}>
                <span className={styles.badge}>{lullaby.lullaby_type}</span>
                <span className={styles.badge}>{lullaby.age_group}</span>
                <span className={styles.duration}>
                  {Math.ceil((lullaby.duration_seconds || 60) / 60)} min
                </span>
              </div>
            </div>

            <button
              className={`${styles.playBtn} ${playing === lullaby.id ? styles.playing : ''}`}
              onClick={() => handlePlay(lullaby)}
              aria-label={playing === lullaby.id ? 'Pause' : 'Play'}
            >
              {playing === lullaby.id ? (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <rect x="6" y="4" width="4" height="16" rx="1"/>
                  <rect x="14" y="4" width="4" height="16" rx="1"/>
                </svg>
              ) : (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M8 5v14l11-7z"/>
                </svg>
              )}
            </button>
          </div>
        ))}
      </div>

      {lullabies.length === 0 && (
        <div className={styles.empty}>
          <p>No lullabies yet. Generate some first!</p>
        </div>
      )}
    </div>
  );
}
